In [1]:
import pickle 
import numpy as np 
import itertools
import pandas as pd
from pathlib import Path

## Make manifests for new minimally reverberant simulation of MIT 46 1004

In [2]:
new_min_rev_dir = Path("/om2/user/imgriff/spatial_audio_pipeline/assets/brir/mit_bldg46room1004_min_reverb")
room_manifest = pd.read_pickle(new_min_rev_dir / 'manifest_room.pdpkl')
room_manifest

,head_azim,head_pos_xyz,index_room,is_outdoor,material_x0,material_x1,material_y0,material_y1,material_z0,material_z1,room_dim_xyz,room_materials
0,0,"[2.3, 3.6, 0.9]",0,False,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,carpet on foam rubber padding,"highly absorptive panels, 1in, 16in below ceiling","[4.66, 5.9, 2.48]","[11, 11, 11, 11, 15, 20]"
1,0,"[3.6, 2.36, 0.9]",1,False,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,carpet on foam rubber padding,"highly absorptive panels, 1in, 16in below ceiling","[5.9, 4.66, 2.48]","[11, 11, 11, 11, 15, 20]"
2,0,"[2.36, 2.3, 0.9]",2,False,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,carpet on foam rubber padding,"highly absorptive panels, 1in, 16in below ceiling","[4.66, 5.9, 2.48]","[11, 11, 11, 11, 15, 20]"
3,0,"[2.3, 2.3, 0.9]",3,False,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,wood panelling on glass fiber blanket,carpet on foam rubber padding,"highly absorptive panels, 1in, 16in below ceiling","[5.9, 4.66, 2.48]","[11, 11, 11, 11, 15, 20]"

In [6]:
saddler_manifest = pd.read_pickle('/om2/user/msaddler/spatial_audio_pipeline/assets/brir/eval/manifest_room.pdpkl')
saddler_manifest

,head_azim,head_pos_xyz,index_room,is_outdoor,material_x0,material_x1,material_y0,material_y1,material_z0,material_z1,room_dim_xyz,room_materials
0,0,"(2.5, 2.5, 2.0)",0,False,"(Anechoic,)","(Anechoic,)","(Anechoic,)","(Anechoic,)","(Anechoic,)","(Anechoic,)","(5.0, 5.0, 4.0)","(26, 26, 26, 26, 26, 26)"
1,0,"(2.5, 2.5, 2.0)",1,False,"(Wood panelling on glass fiber blanket,)","(Wood panelling on glass fiber blanket,)","(Wood panelling on glass fiber blanket,)","(Wood panelling on glass fiber blanket,)","(Carpet on foam rubber padding,)","(Highly absorptive panels, 1"", 16"" below ceili...","(5.0, 5.0, 4.0)","(11, 11, 11, 11, 15, 20)"
2,0,"(2.5, 2.5, 2.0)",2,False,"(Brick,)","(Brick,)","(Brick,)","(Brick,)","(Wood parquet on concrete,)","(Plaster, gypsum, or lime on lath,)","(5.0, 5.0, 4.0)","(1, 1, 1, 1, 12, 16)"
3,0,"(2.5, 2.5, 2.0)",3,False,"(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Linoleum,)","(Acoustic tiles, 0.625"", 16"" below ceiling,)","(5.0, 5.0, 4.0)","(9, 9, 9, 9, 13, 17)"
4,0,"(2.5, 2.5, 2.0)",4,False,"(Concrete, painted,)","(Concrete, painted,)","(Concrete, painted,)","(Concrete, painted,)","(Linoleum,)","(Acoustic tiles, 0.625"", 16"" below ceiling,)","(5.0, 5.0, 4.0)","(2, 2, 2, 2, 13, 17)"
5,0,"(2.3, 3.6, 0.9)",5,False,"(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Concrete, painted,)","(Linoleum,)","(Acoustic tiles, 0.625"", 16"" below ceiling,)","(4.66, 5.9, 2.48)","(9, 9, 9, 2, 13, 17)"
6,0,"(2.33, 2.95, 0.9)",6,False,"(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Concrete, painted,)","(Linoleum,)","(Acoustic tiles, 0.625"", 16"" below ceiling,)","(4.66, 5.9, 2.48)","(9, 9, 9, 2, 13, 17)"
7,0,"(2.3, 3.6, 0.9)",7,False,"(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Linoleum,)","(Acoustic tiles, 0.625"", 16"" below ceiling,)","(4.66, 5.9, 2.48)","(9, 9, 9, 9, 13, 17)"
8,0,"(2.33, 2.95, 0.9)",8,False,"(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Fiberglass wall treatment, 1 in,)","(Linoleum,)","(Acoustic tiles, 0.625"", 16"" below ceiling,)","(4.66, 5.9, 2.48)","(9, 9, 9, 9, 13, 17)"

## Below is how to specify set of test locations, SNRs, and whether to use symmetric distractors

In [4]:

target_azim = 0
elevations = [-20, 0, 40]

# distractor_azims = [0, 10, 30] 
distractor_azims = [0, 5, 10, 20, 30, 40, 60, 90, 120, 150, 180] # Add 30, 60, 90 for comparison to our human experiments - test script handles l/r positioning 


distractor_elevation_deltas = [0, 10, 60] # deltas match new experiment 

snrs = np.linspace(6,-21,num=10)
room_ixs = [0]

### Make sure room path matches the room you want to use 
new_min_rev_dir = Path("/om2/user/imgriff/spatial_audio_pipeline/assets/brir/mit_bldg46room1004_min_reverb")
room_manifest = pd.read_pickle(new_min_rev_dir / 'manifest_room.pdpkl')

def get_room_str(room_ix):
    return  (new_min_rev_dir / f"room{room_ix:04}.hdf5").as_posix()

def get_room_meta_dict(room_ix):
    manifest_path = (new_min_rev_dir / "manifest_brir.pdpkl").as_posix()
    index_room = room_ix
    h5_fn = get_room_str(room_ix)
    return dict(room_manifest=manifest_path, index_room=index_room, h5_fn=h5_fn)

# create dict of trial dicts for azimuth experiment 

azim_cond_dict = {ix:{'target_loc': (0, elev),
                      'distract_loc': [dist_az, elev],
                      'snr': snr,
                      'symmetric_distractor': True,
                      'test_room_meta': get_room_meta_dict(room_ix)} for ix, (elev, dist_az, snr, room_ix) in
              enumerate(itertools.product(*[elevations, distractor_azims, snrs, room_ixs]))} 

n_azim_conds = len(azim_cond_dict)
# create dict of trial dicts for elevation experiment 
elev_cond_dict = {n_azim_conds + ix :{'target_loc': (0, elev),
                      'distract_loc': [0, elev - (np.sign(elev) * elev_delta)],
                      'snr': snr,
                      'symmetric_distractor': True,
                      'test_room_meta': get_room_meta_dict(room_ix)} for ix, (elev, elev_delta, snr, room_ix) in
              enumerate(itertools.product(*[elevations, distractor_elevation_deltas, snrs, room_ixs]))} 


all_cond_dict = {**azim_cond_dict, **elev_cond_dict}
# Assert keys contiguous
assert np.all(np.array(list(all_cond_dict.keys())) == np.arange(len(all_cond_dict)))
print(len(all_cond_dict))

420

### Save tou the test conditions as a pickle file

In [5]:

with open('binaural_test_manifests/human_array_exmpt_sim_w_front_back_21_to_6_dBSNR_min_reverb_mit_room_v02.pkl', 'wb') as f:
    pickle.dump(all_cond_dict, f)