In [5]:
import numpy as np 
import pandas as pd
import h5py
import os 
from IPython.display import Audio

# In this Notebook

* Open munged pdh5 of TIMIT partially parsed timit data to check how much it has been processed 

Files made by Ray for Jenelle's word/speaker/noise dataset. TIMIT did not meet the cutoff for full inclusion, but was partially parsed. Check how far along this processing got

File located here:

`/om4/group/mcdermott/user/raygon/home/projects/public/jsinDataset/assets/data/interim/timit/sr20000`


Pandas to check at `/om4/group/mcdermott/user/raygon/home/projects/public/jsinDataset/assets/data/raw/timit/dataframes/` 

file = `screened_timit_words_munged_wfreq25-100_wlen4_pad2_segments.pdpkl`

In [9]:
## All timit data 

padas_path = '/om4/group/mcdermott/user/raygon/home/projects/public/jsinDataset/assets/data/raw/timit/dataframes/'
pth = 'all_timit_data.pdpkl'

all_timit = pd.read_pickle(os.path.join(padas_path, pth))

In [10]:
all_timit.head()

,corpus,source,speaker_id,speaker_sex,sentence_type,sentence_id,dialect_region,data_split,source_int,dialect_region_int,...,speaker_sex_int,sentence_type_int,sentence_id_int,sr,signal,phoneme,word,sentence,path,signal_length
0,timit,train-dr1-fcjf0-sa1,cjf0,f,sa,1,dr1,train,1680,0,...,0,0,0,16000,"[[3.051850947599719e-05, -3.051850947599719e-0...",start_sample end_sample phoneme 0 ...,start_sample end_sample word 0 ...,...,/home/raygon/deepFerret/data/sources/speech/ti...,46797
1,timit,train-dr1-fcjf0-sa2,cjf0,f,sa,2,dr1,train,1681,0,...,0,0,1111,16000,"[[-3.051850947599719e-05, 0.0, 3.0518509475997...",start_sample end_sample phoneme 0 ...,start_sample end_sample word 0 ...,start_sa...,/home/raygon/deepFerret/data/sources/speech/ti...,34509
2,timit,train-dr1-fcjf0-si1027,cjf0,f,si,1027,dr1,train,1682,0,...,0,1,32,16000,"[[0.00024414807580797754, 0.000152592547379985...",start_sample end_sample phoneme 0 ...,start_sample end_sample word 0 ...,...,/home/raygon/deepFerret/data/sources/speech/ti...,49460
3,timit,train-dr1-fcjf0-si1657,cjf0,f,si,1657,dr1,train,1683,0,...,0,1,731,16000,"[[0.00012207403790398877, 9.155552842799158e-0...",start_sample end_sample phoneme 0 ...,start_sample end_sample word 0 ...,...,/home/raygon/deepFerret/data/sources/speech/ti...,45466
4,timit,train-dr1-fcjf0-si648,cjf0,f,si,648,dr1,train,1684,0,...,0,1,1952,16000,"[[-6.103701895199438e-05, 0.000183111056855983...",start_sample end_sample phoneme 0 ...,start_sample end_sample word 0 ...,...,/home/raygon/deepFerret/data/sources/speech/ti...,57856

In [20]:
all_timit.shape

(6300, 22)

In [35]:
all_timit.columns

Index(['corpus', 'source', 'speaker_id', 'speaker_sex', 'sentence_type',
       'sentence_id', 'dialect_region', 'data_split', 'source_int',
       'dialect_region_int', 'data_split_int', 'speaker_id_int',
       'speaker_sex_int', 'sentence_type_int', 'sentence_id_int', 'sr',
       'signal', 'phoneme', 'word', 'sentence', 'path', 'signal_length'],
      dtype='object')

In [38]:
all_timit.loc[15].word

   start_sample  end_sample      word
0          2280       11640  cyclical
1         11640       23170  programs
2         23600       24935      will
3         24935       30040     never
4         30040       40201   compile

In [19]:
all_timit['word'][0]

    start_sample  end_sample    word
0           3050        5723     she
1           5723       10337     had
2           9190       11517    your
3          11517       16334    dark
4          16334       21199    suit
5          21199       22560      in
6          22560       28064  greasy
7          28064       33360    wash
8          33754       37556   water
9          37556       40313     all
10         40313       44586    year

In [31]:
padas_path = '/om4/group/mcdermott/user/raygon/home/projects/public/jsinDataset/assets/data/raw/timit/dataframes/'
pth = 'screened_timit_words_munged_wfreq25-100_wlen4_pad2_segments.pdpkl'

df = pd.read_pickle(os.path.join(padas_path, pth))

In [41]:
df.head()

,signal_segment,start_sample,end_sample,word,_full_dataset_index,corpus,path,source,sr,signal_length_parent_clip,word_length,num_samples_before,num_samples_after,signal_length_segment
0,"[[0.018829920346690267, 0.00988799707022309, 0...",23600,24935,will,15,timit,/home/raygon/deepFerret/data/sources/speech/ti...,train-dr1-fdaw0-sx146,16000,42087,1335,23600,17152,33335
1,"[[-0.003173924985503708, -0.001434369945371868...",23780,28880,dark,30,timit,/home/raygon/deepFerret/data/sources/speech/ti...,train-dr1-fecd0-sa1,16000,69837,5100,23780,40957,37100
2,"[[9.155552842799158e-05, 0.0001525925473799859...",17794,21519,that,67,timit,/home/raygon/deepFerret/data/sources/speech/ti...,train-dr1-fkfb0-sx348,16000,59290,3725,17794,37771,35725
3,"[[-0.011871700186162909, -0.00967436750389111,...",64907,68120,through,68,timit,/home/raygon/deepFerret/data/sources/speech/ti...,train-dr1-fkfb0-sx438,16000,102093,3213,64907,33973,35213
4,"[[-0.004181035798211615, -0.003509628589739677...",37932,40177,their,94,timit,/home/raygon/deepFerret/data/sources/speech/ti...,train-dr1-fsjk1-si696,16000,56525,2245,37932,16348,34245

In [40]:
Audio(df.signal_segment[0][0], rate=16000)

In [39]:
df.signal_segment[0][0].shape

(33335,)

In [8]:
df.word.unique()

array(['will', 'dark', 'that', 'through', 'their', 'your', 'them', 'this',
       'like', 'have', 'from', 'down', 'water', 'were', 'than', 'about',
       'into', 'would'], dtype=object)

In [2]:
path= '/om4/group/mcdermott/user/raygon/home/projects/public/jsinDataset/assets/data/interim/timit/'
file = 'sr20000/sr20000_timitDataframe_interim.pdh5'

file_path = os.path.join(path, file)

h5 = h5py.File(file_path, 'r')

In [3]:
h5['dataframe_data'].keys()

In [4]:
h5['dataframe_data']['axis0'][:]

array([b'query_str', b'word', b'sentence_id', b'corpus', b'source',
       b'dialect_region', b'speaker_id', b'duration_ms', b'sentence_type',
       b'signal_length', b'sr', b'speaker_sex', b'path', b'sentence',
       b'phoneme', b'n_channels', b'data_split', b'_pre_to_pdh5_index'],
      dtype='|S18')

In [5]:
h5['dataframe_data']['axis1'][:]

array([   0,    1,    2, ..., 6297, 6298, 6299])

In [6]:
h5['dataframe_data']['block0_items'][:]

array([b'signal_length', b'sr', b'n_channels', b'_pre_to_pdh5_index'],
      dtype='|S18')

In [7]:
h5['dataframe_data']['block0_values'][:]

array([[46797, 20000,     1,     0],
       [34509, 20000,     1,     1],
       [49460, 20000,     1,     2],
       ...,
       [36250, 20000,     1,  6297],
       [46592, 20000,     1,  6298],
       [40756, 20000,     1,  6299]])

In [8]:
h5['dataframe_data']['block1_items'][:]

array([b'query_str', b'word', b'sentence_id', b'corpus', b'source',
       b'dialect_region', b'speaker_id', b'duration_ms', b'sentence_type',
       b'speaker_sex', b'path', b'sentence', b'phoneme', b'data_split'],
      dtype='|S14')

In [51]:
np.unique(h5['dataframe_data']['block1_values'][0])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255], dtype=uint8)

In [10]:
h5.keys()

In [11]:
h5['ndarray_data']['signal']

In [12]:

Audio(h5['ndarray_data']['signal'][0], rate=20000)

In [14]:

timit_df = pd.read_pickle(os.path.join(path,'timitWordsDataframe_interim.pdpkl'))

In [15]:
timit_df[timit_df._full_dataset_index == 0]

,start_sample,end_sample,word,_full_dataset_index,corpus,path,source,speaker,sr,signal_length,duration_ms,n_channels,word_length_samples,num_samples_before,num_samples_after,start_ms,end_ms
0,3050,5723,she,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,2673,3050,41074,0.190625,0.357687
1,5723,10337,had,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,4614,5723,36460,0.357687,0.646062
2,9190,11517,your,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,2327,9190,35280,0.574375,0.719812
3,11517,16334,dark,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,4817,11517,30463,0.719812,1.020875
4,16334,21199,suit,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,4865,16334,25598,1.020875,1.324938
5,21199,22560,in,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,1361,21199,24237,1.324938,1.410000
6,22560,28064,greasy,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,5504,22560,18733,1.410000,1.754000
7,28064,33360,wash,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,5296,28064,13437,1.754000,2.085000
8,33754,37556,water,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,3802,33754,9241,2.109625,2.347250
9,37556,40313,all,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,2757,37556,6484,2.347250,2.519563
10,40313,44586,year,0,timit,/home/raygon/projects/user/jfeather/jsinDatase...,train-dr1-fcjf0-sa1,fcjf0,16000,46797,2924.8125,1,4273,40313,2211,2.519563,2.786625

In [49]:
timit_df.path.iloc[0]

'/home/raygon/projects/user/jfeather/jsinDataset/assets/data/raw/timit/train/dr1/fcjf0/sa1.wav'

In [52]:
timit_df.iloc[128]

start_sample                                                       24440
end_sample                                                         28745
word                                                                 set
_full_dataset_index                                                   13
corpus                                                             timit
path                   /home/raygon/projects/user/jfeather/jsinDatase...
source                                            train-dr1-fdaw0-si1406
speaker                                                            fdaw0
sr                                                                 16000
signal_length                                                      40653
duration_ms                                                    2540.8125
n_channels                                                             1
word_length_samples                                                 4305
num_samples_before                                                 24440
num_samples_after                                                  11908
start_ms                                                          1.5275
end_ms                                                          1.796563
Name: 4, dtype: object

In [34]:
def convert_frames(frame_n, in_sr=16_000, out_sr=20_000):
    return int(out_sr/in_sr * frame_n)

In [37]:
convert_frames(3050)

3812

In [41]:
Audio(h5['ndarray_data']['signal'][0][5723:], rate=20000)

In [44]:
h5['ndarray_data']['signal'][0].shape[0] / 20_000

2.92485

In [52]:
path= '/om4/group/mcdermott/user/raygon/home/projects/public/jsinDataset/assets/data/interim/timit/'
file = 'timitDataframe_interim_sr16000.pdh5'

file_path = os.path.join(path, file)

h51 = h5py.File(file_path, 'r')

In [59]:
h51['dataframe_data'].keys()

In [65]:
h51['dataframe_data']['block1_items'][:]

array([b'query_str', b'word', b'sentence_id', b'corpus', b'source',
       b'dialect_region', b'speaker_id', b'duration_ms', b'sentence_type',
       b'speaker_sex', b'path', b'sentence', b'phoneme', b'data_split'],
      dtype='|S14')

In [67]:
import pickle

word_and_speaker_encodings = pickle.load( open( "/om4/group/mcdermott/user/jfeather/projects/model_metamers/figure_generation_notebooks/word_and_speaker_encodings_jsinv3.pckl", "rb" )) 
class_map = word_and_speaker_encodings['word_idx_to_word']

In [75]:
class_map[h5['dataframe_data']['block1_values'][0][3]]

'between'