In [1]:
import pandas as pd
import numpy as np 
from pathlib import Path
from os.path import join, getsize
import sys
sys.path.append('/om4/group/mcdermott/user/imgriff/projects/espnet/')
from espnet
import kaldiio # for use with kaldi type format

In [ ]:
import sys
sys.path.append('/om4/group/mcdermott/user/imgriff/projects/espnet')
import espnet.espnet2.

In [2]:
path = '/om2/data/public/GigaSpeech/'

split = 'XL'
# split = 'DEV'
audio_path = Path(join(path, 'audio'))
samp_rate = 16000
manifest_path = Path(f"{path}/data/{split}.csv")

In [3]:
!ls {path}/data/gigaspeech_train_xl

reco2dur  segments  spk2utt  text  utt2dur  utt2spk  wav.scp

In [4]:
# Use segments with load_scp for full split in one go:
train_scp_path = Path(path, 'data', 'gigaspeech_train_xl', 'wav.scp').as_posix()
train_seg_path = Path(path, 'data', 'gigaspeech_train_xl', 'segments').as_posix()

scp_reader = kaldiio.load_scp(train_scp_path, segments=train_seg_path)

In [5]:
len(scp_reader)

8282988

In [27]:
list(scp_reader.keys())[0]

'AUD0000000003_S0000001'

In [31]:
scp_reader['AUD0000000003_S0000001']

FileNotFoundError: [Errno 2] No such file or directory: 'dump/raw/org/train/data/format.1/AUD0000000003_S0000001.flac'

In [21]:
wavscp_k = kaldiio.load_scp(Path(path,'data','wav.scp').as_posix())
# wavscp = pd.read_csv(Path(path,'data','wav.scp'), header=None,
#                                  names=['speaker', 'wav_path'], sep='\t',
#                                  )

In [30]:
wavscp.set_index('speaker')['wav_path'].to_dict()

{'POD0000000001': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000001.wav',
 'POD0000000002': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000002.wav',
 'POD0000000003': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000003.wav',
 'POD0000000004': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000004.wav',
 'POD0000000005': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000005.wav',
 'POD0000000006': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000006.wav',
 'POD0000000007': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000007.wav',
 'POD0000000008': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000008.wav',
 'POD0000000009': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000009.wav',
 'POD0000000010': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000010.wav',
 'POD0000000011': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000011.wav',
 'POD0000000012': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000012.wav',
 'POD0000000013': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000013.wav',
 'POD0000000014': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000014.wav',
 'POD0000000015': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000015.wav',
 'POD0000000016': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000016.wav',
 'POD0000000017': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000017.wav',
 'POD0000000018': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000018.wav',
 'POD0000000019': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000019.wav',
 'POD0000000020': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000020.wav',
 'POD0000000021': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000021.wav',
 'POD0000000022': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000022.wav',
 'POD0000000023': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000023.wav',
 'POD0000000024': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000024.wav',
 'POD0000000025': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000025.wav',
 'POD0000000026': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000026.wav',
 'POD0000000027': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000027.wav',
 'POD0000000028': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000028.wav',
 'POD0000000029': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000029.wav',
 'POD0000000030': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000030.wav',
 'POD0000000031': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000031.wav',
 'POD0000000032': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000032.wav',
 'POD0000000033': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000033.wav',
 'POD0000000034': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000034.wav',
 'POD0000000035': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000035.wav',
 'POD0000000036': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000036.wav',
 'POD0000000037': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000037.wav',
 'POD0000000038': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000038.wav',
 'POD0000000039': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000039.wav',
 'POD0000000040': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000040.wav',
 'POD0000000041': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000041.wav',
 'POD0000000042': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000042.wav',
 'POD0000000043': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000043.wav',
 'POD0000000044': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000044.wav',
 'POD0000000046': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000046.wav',
 'POD0000000047': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000047.wav',
 'POD0000000048': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000048.wav',
 'POD0000000049': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000049.wav',
 'POD0000000050': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000050.wav',
 'POD0000000051': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000051.wav',
 'POD0000000052': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000052.wav',
 'POD0000000053': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000053.wav',
 'POD0000000054': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000054.wav',
 'POD0000000055': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000055.wav',
 'POD0000000056': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000056.wav',
 'POD0000000057': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000057.wav',
 'POD0000000058': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000058.wav',
 'POD0000000059': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000059.wav',
 'POD0000000060': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000060.wav',
 'POD0000000061': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000061.wav',
 'POD0000000062': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000062.wav',
 'POD0000000063': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000063.wav',
 'POD0000000064': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000064.wav',
 'POD0000000065': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000065.wav',
 'POD0000000066': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000066.wav',
 'POD0000000067': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000067.wav',
 'POD0000000068': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000068.wav',
 'POD0000000069': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000069.wav',
 'POD0000000070': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000070.wav',
 'POD0000000071': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000071.wav',
 'POD0000000072': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000072.wav',
 'POD0000000073': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000073.wav',
 'POD0000000074': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000074.wav',
 'POD0000000075': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000075.wav',
 'POD0000000076': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000076.wav',
 'POD0000000077': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000077.wav',
 'POD0000000078': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000078.wav',
 'POD0000000079': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000079.wav',
 'POD0000000080': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000080.wav',
 'POD0000000081': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000081.wav',
 'POD0000000082': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000082.wav',
 'POD0000000083': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000083.wav',
 'POD0000000084': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000084.wav',
 'POD0000000085': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000085.wav',
 'POD0000000086': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000086.wav',
 'POD0000000087': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000087.wav',
 'POD0000000088': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000088.wav',
 'POD0000000089': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000089.wav',
 'POD0000000090': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000090.wav',
 'POD0000000091': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000091.wav',
 'POD0000000092': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000092.wav',
 'POD0000000093': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000093.wav',
 'POD0000000094': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000094.wav',
 'POD0000000095': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000095.wav',
 'POD0000000096': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000096.wav',
 'POD0000000097': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000097.wav',
 'POD0000000098': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000098.wav',
 'POD0000000099': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000099.wav',
 'POD0000000100': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0001/POD0000000100.wav',
 'POD0000000101': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000101.wav',
 'POD0000000102': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000102.wav',
 'POD0000000103': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000103.wav',
 'POD0000000104': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000104.wav',
 'POD0000000105': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000105.wav',
 'POD0000000106': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000106.wav',
 'POD0000000107': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000107.wav',
 'POD0000000108': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000108.wav',
 'POD0000000109': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000109.wav',
 'POD0000000110': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000110.wav',
 'POD0000000111': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000111.wav',
 'POD0000000112': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000112.wav',
 'POD0000000113': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000113.wav',
 'POD0000000114': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000114.wav',
 'POD0000000115': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000115.wav',
 'POD0000000116': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000116.wav',
 'POD0000000117': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000117.wav',
 'POD0000000118': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000118.wav',
 'POD0000000119': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000119.wav',
 'POD0000000120': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000120.wav',
 'POD0000000121': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000121.wav',
 'POD0000000122': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000122.wav',
 'POD0000000123': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000123.wav',
 'POD0000000124': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000124.wav',
 'POD0000000125': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000125.wav',
 'POD0000000126': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000126.wav',
 'POD0000000127': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000127.wav',
 'POD0000000128': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000128.wav',
 'POD0000000129': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000129.wav',
 'POD0000000130': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000130.wav',
 'POD0000000131': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000131.wav',
 'POD0000000132': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000132.wav',
 'POD0000000133': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000133.wav',
 'POD0000000134': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000134.wav',
 'POD0000000135': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000135.wav',
 'POD0000000136': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000136.wav',
 'POD0000000137': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000137.wav',
 'POD0000000138': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000138.wav',
 'POD0000000139': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000139.wav',
 'POD0000000140': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000140.wav',
 'POD0000000141': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000141.wav',
 'POD0000000142': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000142.wav',
 'POD0000000143': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000143.wav',
 'POD0000000144': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000144.wav',
 'POD0000000145': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000145.wav',
 'POD0000000146': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000146.wav',
 'POD0000000147': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000147.wav',
 'POD0000000148': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000148.wav',
 'POD0000000149': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000149.wav',
 'POD0000000150': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000150.wav',
 'POD0000000151': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000151.wav',
 'POD0000000152': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000152.wav',
 'POD0000000153': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000153.wav',
 'POD0000000154': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000154.wav',
 'POD0000000155': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000155.wav',
 'POD0000000156': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000156.wav',
 'POD0000000157': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000157.wav',
 'POD0000000158': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000158.wav',
 'POD0000000159': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000159.wav',
 'POD0000000160': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000160.wav',
 'POD0000000161': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000161.wav',
 'POD0000000162': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000162.wav',
 'POD0000000163': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000163.wav',
 'POD0000000164': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000164.wav',
 'POD0000000165': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000165.wav',
 'POD0000000166': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000166.wav',
 'POD0000000167': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000167.wav',
 'POD0000000168': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000168.wav',
 'POD0000000169': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000169.wav',
 'POD0000000170': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000170.wav',
 'POD0000000171': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000171.wav',
 'POD0000000172': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000172.wav',
 'POD0000000173': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000173.wav',
 'POD0000000174': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000174.wav',
 'POD0000000175': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000175.wav',
 'POD0000000176': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000176.wav',
 'POD0000000177': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000177.wav',
 'POD0000000178': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000178.wav',
 'POD0000000179': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000179.wav',
 'POD0000000180': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000180.wav',
 'POD0000000181': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000181.wav',
 'POD0000000182': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000182.wav',
 'POD0000000183': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000183.wav',
 'POD0000000184': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000184.wav',
 'POD0000000185': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000185.wav',
 'POD0000000186': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000186.wav',
 'POD0000000187': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000187.wav',
 'POD0000000188': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000188.wav',
 'POD0000000189': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000189.wav',
 'POD0000000190': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000190.wav',
 'POD0000000191': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000191.wav',
 'POD0000000192': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000192.wav',
 'POD0000000193': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000193.wav',
 'POD0000000194': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000194.wav',
 'POD0000000195': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000195.wav',
 'POD0000000196': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000196.wav',
 'POD0000000197': '/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/podcast/P0002/POD0000000197.wav',

In [5]:
manifest_path

PosixPath('/om2/data/public/GigaSpeech/data/XL.csv')

In [5]:
audio_path

PosixPath('/om2/data/public/GigaSpeech/audio')

In [6]:
manifest = pd.read_csv(manifest_path, sep='\t',
                               usecols=['wav_filename', 'speaker', 'transcript'])

In [7]:
manifest = manifest[~manifest.isna().any(axis=1)]

In [9]:
sorted(manifest.to_numpy(), key= lambda x: len(x[1]))

[array(['POD0000000104_S0000114', 'I', 'POD0000000104'], dtype=object),
 array(['POD0000000125_S0000273', 'I', 'POD0000000125'], dtype=object),
 array(['POD0000000228_S0000160', 'I', 'POD0000000228'], dtype=object),
 array(['POD0000000231_S0000254', 'I', 'POD0000000231'], dtype=object),
 array(['POD0000000240_S0000375', 'I', 'POD0000000240'], dtype=object),
 array(['POD0000000286_S0000522', 'A', 'POD0000000286'], dtype=object),
 array(['POD0000000318_S0000125', 'I', 'POD0000000318'], dtype=object),
 array(['POD0000000406_S0000329', 'I', 'POD0000000406'], dtype=object),
 array(['POD0000000408_S0000353', 'I', 'POD0000000408'], dtype=object),
 array(['POD0000000417_S0000329', 'I', 'POD0000000417'], dtype=object),
 array(['POD0000000431_S0000441', 'I', 'POD0000000431'], dtype=object),
 array(['POD0000000451_S0000340', 'I', 'POD0000000451'], dtype=object),
 array(['POD0000000462_S0000044', 'I', 'POD0000000462'], dtype=object),
 array(['POD0000000486_S0000044', 'I', 'POD0000000486'], dtype=object),
 array(['POD0000000516_S0000329', 'I', 'POD0000000516'], dtype=object),
 array(['POD0000000518_S0000133', 'A', 'POD0000000518'], dtype=object),
 array(['POD0000000519_S0000105', 'I', 'POD0000000519'], dtype=object),
 array(['POD0000000546_S0000251', 'I', 'POD0000000546'], dtype=object),
 array(['POD0000000552_S0000408', 'I', 'POD0000000552'], dtype=object),
 array(['POD0000000558_S0000247', 'G', 'POD0000000558'], dtype=object),
 array(['POD0000000575_S0000435', 'I', 'POD0000000575'], dtype=object),
 array(['POD0000000579_S0000337', 'I', 'POD0000000579'], dtype=object),
 array(['POD0000000590_S0000251', 'I', 'POD0000000590'], dtype=object),
 array(['POD0000000594_S0000352', 'I', 'POD0000000594'], dtype=object),
 array(['POD0000000600_S0000252', 'I', 'POD0000000600'], dtype=object),
 array(['POD0000000606_S0000294', 'I', 'POD0000000606'], dtype=object),
 array(['POD0000000644_S0000353', 'I', 'POD0000000644'], dtype=object),
 array(['POD0000000651_S0000434', 'I', 'POD0000000651'], dtype=object),
 array(['POD0000000688_S0000441', 'I', 'POD0000000688'], dtype=object),
 array(['POD0000000690_S0000104', 'I', 'POD0000000690'], dtype=object),
 array(['POD0000000699_S0000329', 'I', 'POD0000000699'], dtype=object),
 array(['POD0000000737_S0000105', 'I', 'POD0000000737'], dtype=object),
 array(['POD0000000748_S0000339', 'I', 'POD0000000748'], dtype=object),
 array(['POD0000000750_S0000408', 'I', 'POD0000000750'], dtype=object),
 array(['POD0000000776_S0000134', 'A', 'POD0000000776'], dtype=object),
 array(['POD0000000777_S0000336', 'I', 'POD0000000777'], dtype=object),
 array(['POD0000000829_S0000159', 'I', 'POD0000000829'], dtype=object),
 array(['POD0000000870_S0000336', 'I', 'POD0000000870'], dtype=object),
 array(['POD0000000928_S0000336', 'I', 'POD0000000928'], dtype=object),
 array(['POD0000000933_S0000352', 'I', 'POD0000000933'], dtype=object),
 array(['POD0000000937_S0000250', 'I', 'POD0000000937'], dtype=object),
 array(['POD0000000983_S0000105', 'I', 'POD0000000983'], dtype=object),
 array(['POD0000001001_S0000354', 'I', 'POD0000001001'], dtype=object),
 array(['POD0000001003_S0000339', 'I', 'POD0000001003'], dtype=object),
 array(['POD0000001087_S0000339', 'I', 'POD0000001087'], dtype=object),
 array(['POD0000001113_S0000251', 'I', 'POD0000001113'], dtype=object),
 array(['POD0000001116_S0000351', 'I', 'POD0000001116'], dtype=object),
 array(['POD0000001123_S0000293', 'I', 'POD0000001123'], dtype=object),
 array(['POD0000001144_S0000434', 'I', 'POD0000001144'], dtype=object),
 array(['POD0000001146_S0000128', 'I', 'POD0000001146'], dtype=object),
 array(['POD0000001147_S0000337', 'I', 'POD0000001147'], dtype=object),
 array(['POD0000001169_S0000250', 'I', 'POD0000001169'], dtype=object),
 array(['POD0000001173_S0000339', 'I', 'POD0000001173'], dtype=object),
 array(['POD0000001178_S0000105', 'I', 'POD0000001178'], dtype=object),
 array(['POD0000001184_S0000293', 'I', 'POD0000001184'], dtype=object),
 array(['POD0000001203_S0000133', 'A', 'POD0000001203'], dtype=object),
 array(['POD0000001236_S0000352', 'I', 'POD0000001236'], dtype=object),
 array(['POD0000001264_S0000409', 'I', 'POD0000001264'], dtype=object),
 array(['POD0000001287_S0000044', 'I', 'POD0000001287'], dtype=object),
 array(['POD0000001304_S0000337', 'I', 'POD0000001304'], dtype=object),
 array(['POD0000001309_S0000329', 'I', 'POD0000001309'], dtype=object),
 array(['POD0000001314_S0000251', 'I', 'POD0000001314'], dtype=object),
 array(['POD0000001315_S0000353', 'I', 'POD0000001315'], dtype=object),
 array(['POD0000001345_S0000329', 'I', 'POD0000001345'], dtype=object),
 array(['POD0000001348_S0000352', 'I', 'POD0000001348'], dtype=object),
 array(['POD0000001364_S0000435', 'I', 'POD0000001364'], dtype=object),
 array(['POD0000001372_S0000442', 'I', 'POD0000001372'], dtype=object),
 array(['POD0000001387_S0000435', 'I', 'POD0000001387'], dtype=object),
 array(['POD0000001404_S0000439', 'I', 'POD0000001404'], dtype=object),
 array(['POD0000001405_S0000428', 'I', 'POD0000001405'], dtype=object),
 array(['POD0000001410_S0000386', 'I', 'POD0000001410'], dtype=object),
 array(['POD0000001413_S0000467', 'I', 'POD0000001413'], dtype=object),
 array(['POD0000001415_S0000202', 'I', 'POD0000001415'], dtype=object),
 array(['POD0000001415_S0000729', 'I', 'POD0000001415'], dtype=object),
 array(['POD0000001424_S0000654', 'A', 'POD0000001424'], dtype=object),
 array(['POD0000001428_S0000493', 'I', 'POD0000001428'], dtype=object),
 array(['POD0000001431_S0000044', 'I', 'POD0000001431'], dtype=object),
 array(['POD0000001431_S0000149', 'I', 'POD0000001431'], dtype=object),
 array(['POD0000001439_S0000540', 'I', 'POD0000001439'], dtype=object),
 array(['POD0000001822_S0000045', 'I', 'POD0000001822'], dtype=object),
 array(['POD0000002131_S0000009', 'I', 'POD0000002131'], dtype=object),
 array(['POD0000002837_S0000075', 'I', 'POD0000002837'], dtype=object),
 array(['POD0000002937_S0000190', 'I', 'POD0000002937'], dtype=object),
 array(['POD0000003161_S0000170', 'I', 'POD0000003161'], dtype=object),
 array(['POD0000003287_S0000276', 'I', 'POD0000003287'], dtype=object),
 array(['POD0000003344_S0000251', 'I', 'POD0000003344'], dtype=object),
 array(['POD0000003353_S0000113', 'I', 'POD0000003353'], dtype=object),
 array(['POD0000003356_S0000283', 'I', 'POD0000003356'], dtype=object),
 array(['POD0000003362_S0000024', 'I', 'POD0000003362'], dtype=object),
 array(['POD0000003376_S0000325', 'A', 'POD0000003376'], dtype=object),
 array(['POD0000003396_S0000186', 'I', 'POD0000003396'], dtype=object),
 array(['POD0000003399_S0000341', 'I', 'POD0000003399'], dtype=object),
 array(['POD0000003426_S0000141', 'I', 'POD0000003426'], dtype=object),
 array(['POD0000003468_S0000248', 'I', 'POD0000003468'], dtype=object),
 array(['POD0000003511_S0000248', 'I', 'POD0000003511'], dtype=object),
 array(['POD0000003516_S0000281', 'I', 'POD0000003516'], dtype=object),
 array(['POD0000003550_S0000264', 'I', 'POD0000003550'], dtype=object),
 array(['POD0000003571_S0000334', 'I', 'POD0000003571'], dtype=object),
 array(['POD0000003591_S0000279', 'I', 'POD0000003591'], dtype=object),
 array(['POD0000003982_S0000169', 'A', 'POD0000003982'], dtype=object),
 array(['POD0000004065_S0000079', 'I', 'POD0000004065'], dtype=object),
 array(['POD0000004305_S0000038', 'I', 'POD0000004305'], dtype=object),
 array(['POD0000004779_S0000029', 'I', 'POD0000004779'], dtype=object),
 array(['POD0000004819_S0000152', 'I', 'POD0000004819'], dtype=object),
 array(['POD0000004883_S0000230', 'I', 'POD0000004883'], dtype=object),
 array(['POD0000004931_S0000181', 'I', 'POD0000004931'], dtype=object),
 array(['POD0000004943_S0000096', 'I', 'POD0000004943'], dtype=object),
 array(['POD0000004958_S0000000', 'I', 'POD0000004958'], dtype=object),
 array(['POD0000004961_S0000000', 'I', 'POD0000004961'], dtype=object),
 array(['POD0000004968_S0000000', 'I', 'POD0000004968'], dtype=object),
 array(['POD0000004976_S0000000', 'I', 'POD0000004976'], dtype=object),
 array(['POD0000004983_S0000000', 'I', 'POD0000004983'], dtype=object),
 array(['POD0000004986_S0000000', 'I', 'POD0000004986'], dtype=object),
 array(['POD0000004988_S0000000', 'I', 'POD0000004988'], dtype=object),
 array(['POD0000004989_S0000062', 'I', 'POD0000004989'], dtype=object),
 array(['POD0000004999_S0000081', 'I', 'POD0000004999'], dtype=object),
 array(['POD0000005001_S0000001', 'I', 'POD0000005001'], dtype=object),
 array(['POD0000005002_S0000000', 'I', 'POD0000005002'], dtype=object),
 array(['POD0000005002_S0000117', 'I', 'POD0000005002'], dtype=object),
 array(['POD0000005011_S0000000', 'I', 'POD0000005011'], dtype=object),
 array(['POD0000005014_S0000000', 'I', 'POD0000005014'], dtype=object),
 array(['POD0000005017_S0000000', 'I', 'POD0000005017'], dtype=object),
 array(['POD0000005021_S0000000', 'I', 'POD0000005021'], dtype=object),
 array(['POD0000005026_S0000107', 'I', 'POD0000005026'], dtype=object),
 array(['POD0000005029_S0000150', 'I', 'POD0000005029'], dtype=object),
 array(['POD0000005031_S0000000', 'I', 'POD0000005031'], dtype=object),
 array(['POD0000005055_S0000047', 'I', 'POD0000005055'], dtype=object),
 array(['POD0000005082_S0000030', 'I', 'POD0000005082'], dtype=object),
 array(['POD0000005088_S0000117', 'I', 'POD0000005088'], dtype=object),
 array(['POD0000005089_S0000000', 'I', 'POD0000005089'], dtype=object),
 array(['POD0000005090_S0000000', 'I', 'POD0000005090'], dtype=object),
 array(['POD0000005115_S0000080', 'I', 'POD0000005115'], dtype=object),
 array(['POD0000005133_S0000030', 'A', 'POD0000005133'], dtype=object),
 array(['POD0000005222_S0000008', 'I', 'POD0000005222'], dtype=object),
 array(['POD0000005433_S0000277', 'I', 'POD0000005433'], dtype=object),
 array(['POD0000005453_S0000339', 'I', 'POD0000005453'], dtype=object),
 array(['POD0000005541_S0000253', 'I', 'POD0000005541'], dtype=object),
 array(['POD0000005573_S0000335', 'A', 'POD0000005573'], dtype=object),
 array(['POD0000005579_S0000574', 'I', 'POD0000005579'], dtype=object),
 array(['POD0000005581_S0000971', 'I', 'POD0000005581'], dtype=object),
 array(['POD0000005588_S0000157', 'A', 'POD0000005588'], dtype=object),
 array(['POD0000005608_S0000587', 'A', 'POD0000005608'], dtype=object),
 array(['POD0000005630_S0000479', 'I', 'POD0000005630'], dtype=object),
 array(['POD0000005643_S0000428', 'I', 'POD0000005643'], dtype=object),
 array(['POD0000005654_S0000104', 'A', 'POD0000005654'], dtype=object),
 array(['POD0000005658_S0000015', 'A', 'POD0000005658'], dtype=object),
 array(['POD0000005672_S0000127', 'I', 'POD0000005672'], dtype=object),
 array(['POD0000005672_S0000134', 'I', 'POD0000005672'], dtype=object),
 array(['POD0000005672_S0000263', 'I', 'POD0000005672'], dtype=object),
 array(['POD0000005674_S0000055', 'I', 'POD0000005674'], dtype=object),
 array(['POD0000005674_S0000937', 'I', 'POD0000005674'], dtype=object),
 array(['POD0000005677_S0000905', 'A', 'POD0000005677'], dtype=object),
 array(['POD0000005678_S0001119', 'I', 'POD0000005678'], dtype=object),
 array(['POD0000005680_S0000908', 'A', 'POD0000005680'], dtype=object),
 array(['POD0000005681_S0001641', 'I', 'POD0000005681'], dtype=object),
 array(['POD0000005683_S0000134', 'A', 'POD0000005683'], dtype=object),
 array(['POD0000005683_S0000378', 'A', 'POD0000005683'], dtype=object),
 array(['POD0000005691_S0000547', 'A', 'POD0000005691'], dtype=object),
 array(['POD0000005693_S0000662', 'A', 'POD0000005693'], dtype=object),
 array(['POD0000005700_S0000148', 'A', 'POD0000005700'], dtype=object),
 array(['POD0000005700_S0000268', 'I', 'POD0000005700'], dtype=object),
 array(['POD0000005700_S0001097', 'A', 'POD0000005700'], dtype=object),
 array(['POD0000005701_S0000143', 'I', 'POD0000005701'], dtype=object),
 array(['POD0000005704_S0000726', 'I', 'POD0000005704'], dtype=object),
 array(['POD0000005707_S0000116', 'A', 'POD0000005707'], dtype=object),
 array(['POD0000005708_S0000018', 'I', 'POD0000005708'], dtype=object),
 array(['POD0000005708_S0001155', 'I', 'POD0000005708'], dtype=object),
 array(['POD0000005711_S0000506', 'I', 'POD0000005711'], dtype=object),
 array(['POD0000005711_S0000614', 'I', 'POD0000005711'], dtype=object),
 array(['POD0000005712_S0000296', 'A', 'POD0000005712'], dtype=object),
 array(['POD0000005713_S0000930', 'I', 'POD0000005713'], dtype=object),
 array(['POD0000005714_S0000371', 'A', 'POD0000005714'], dtype=object),
 array(['POD0000005715_S0000489', 'A', 'POD0000005715'], dtype=object),
 array(['POD0000005717_S0001181', 'I', 'POD0000005717'], dtype=object),
 array(['POD0000005717_S0001287', 'I', 'POD0000005717'], dtype=object),
 array(['POD0000005717_S0001753', 'I', 'POD0000005717'], dtype=object),
 array(['POD0000005722_S0000806', 'I', 'POD0000005722'], dtype=object),
 array(['POD0000005722_S0000952', 'I', 'POD0000005722'], dtype=object),
 array(['POD0000005725_S0000991', 'I', 'POD0000005725'], dtype=object),
 array(['POD0000005728_S0000334', 'A', 'POD0000005728'], dtype=object),
 array(['POD0000005732_S0000652', 'I', 'POD0000005732'], dtype=object),
 array(['POD0000005738_S0000281', 'O', 'POD0000005738'], dtype=object),
 array(['POD0000005749_S0000059', 'I', 'POD0000005749'], dtype=object),
 array(['POD0000005769_S0000085', 'I', 'POD0000005769'], dtype=object),
 array(['POD0000005769_S0001202', 'I', 'POD0000005769'], dtype=object),
 array(['POD0000005787_S0000174', 'A', 'POD0000005787'], dtype=object),
 array(['POD0000005799_S0000353', 'O', 'POD0000005799'], dtype=object),
 array(['POD0000005806_S0000396', 'A', 'POD0000005806'], dtype=object),
 array(['POD0000005806_S0000422', 'A', 'POD0000005806'], dtype=object),
 array(['POD0000005806_S0000456', 'A', 'POD0000005806'], dtype=object),
 array(['POD0000005819_S0000115', 'I', 'POD0000005819'], dtype=object),
 array(['POD0000005819_S0001190', 'A', 'POD0000005819'], dtype=object),
 array(['POD0000005823_S0000455', 'A', 'POD0000005823'], dtype=object),
 array(['POD0000005838_S0000924', 'I', 'POD0000005838'], dtype=object),
 array(['POD0000005846_S0000606', 'I', 'POD0000005846'], dtype=object),
 array(['POD0000005846_S0001643', 'I', 'POD0000005846'], dtype=object),
 array(['POD0000005846_S0001667', 'I', 'POD0000005846'], dtype=object),
 array(['POD0000005855_S0000375', 'I', 'POD0000005855'], dtype=object),
 array(['POD0000005855_S0000749', 'I', 'POD0000005855'], dtype=object),
 array(['POD0000005863_S0000886', 'I', 'POD0000005863'], dtype=object),
 array(['POD0000005863_S0000895', 'I', 'POD0000005863'], dtype=object),
 array(['POD0000005863_S0000960', 'I', 'POD0000005863'], dtype=object),
 array(['POD0000005867_S0000763', 'I', 'POD0000005867'], dtype=object),
 array(['POD0000005877_S0000758', 'A', 'POD0000005877'], dtype=object),
 array(['POD0000005888_S0000003', 'A', 'POD0000005888'], dtype=object),
 array(['POD0000005896_S0000393', 'O', 'POD0000005896'], dtype=object),
 array(['POD0000006990_S0000383', 'I', 'POD0000006990'], dtype=object),
 array(['POD0000006990_S0000490', 'I', 'POD0000006990'], dtype=object),
 array(['POD0000006991_S0000471', 'I', 'POD0000006991'], dtype=object),
 array(['POD0000006993_S0001322', 'I', 'POD0000006993'], dtype=object),
 array(['POD0000006996_S0000595', 'I', 'POD0000006996'], dtype=object),
 array(['POD0000007002_S0001190', 'I', 'POD0000007002'], dtype=object),
 array(['POD0000007008_S0000312', 'I', 'POD0000007008'], dtype=object),
 array(['POD0000007025_S0001170', 'I', 'POD0000007025'], dtype=object),
 array(['POD0000007229_S0000196', 'I', 'POD0000007229'], dtype=object),
 array(['POD0000007232_S0001319', 'I', 'POD0000007232'], dtype=object),
 array(['POD0000007237_S0000821', 'I', 'POD0000007237'], dtype=object),
 array(['POD0000007253_S0000479', 'I', 'POD0000007253'], dtype=object),
 array(['POD0000007270_S0000507', 'I', 'POD0000007270'], dtype=object),
 array(['POD0000007277_S0000533', 'I', 'POD0000007277'], dtype=object),
 array(['POD0000007279_S0000661', 'I', 'POD0000007279'], dtype=object),
 array(['POD0000007288_S0000070', 'I', 'POD0000007288'], dtype=object),
 array(['POD0000007309_S0000048', 'I', 'POD0000007309'], dtype=object),
 array(['POD0000007332_S0000145', 'I', 'POD0000007332'], dtype=object),
 array(['POD0000007333_S0000261', 'I', 'POD0000007333'], dtype=object),
 array(['POD0000007337_S0000304', 'I', 'POD0000007337'], dtype=object),
 array(['POD0000007339_S0000378', 'I', 'POD0000007339'], dtype=object),
 array(['POD0000007339_S0000424', 'I', 'POD0000007339'], dtype=object),
 array(['POD0000007354_S0000277', 'I', 'POD0000007354'], dtype=object),
 array(['POD0000007369_S0000248', 'I', 'POD0000007369'], dtype=object),
 array(['POD0000007377_S0000041', 'I', 'POD0000007377'], dtype=object),
 array(['POD0000007377_S0000187', 'I', 'POD0000007377'], dtype=object),
 array(['POD0000007380_S0000300', 'I', 'POD0000007380'], dtype=object),
 array(['POD0000007384_S0000063', 'O', 'POD0000007384'], dtype=object),
 array(['POD0000007384_S0000118', 'I', 'POD0000007384'], dtype=object),
 array(['POD0000007386_S0000088', 'Y', 'POD0000007386'], dtype=object),
 array(['POD0000007386_S0000155', 'Y', 'POD0000007386'], dtype=object),
 array(['POD0000007387_S0000161', 'I', 'POD0000007387'], dtype=object),
 array(['POD0000007387_S0000179', 'O', 'POD0000007387'], dtype=object),
 array(['POD0000007389_S0000182', 'U', 'POD0000007389'], dtype=object),
 array(['POD0000007389_S0000197', 'O', 'POD0000007389'], dtype=object),
 array(['POD0000007391_S0000167', 'I', 'POD0000007391'], dtype=object),
 array(['POD0000007418_S0000417', 'I', 'POD0000007418'], dtype=object),
 array(['POD0000007458_S0000156', 'I', 'POD0000007458'], dtype=object),
 array(['POD0000007628_S0000169', 'I', 'POD0000007628'], dtype=object),
 array(['POD0000007649_S0000272', 'I', 'POD0000007649'], dtype=object),
 array(['POD0000007678_S0000672', 'A', 'POD0000007678'], dtype=object),
 array(['POD0000007692_S0000729', 'I', 'POD0000007692'], dtype=object),
 array(['POD0000007696_S0000269', 'A', 'POD0000007696'], dtype=object),
 array(['POD0000007724_S0000261', 'I', 'POD0000007724'], dtype=object),
 array(['POD0000007745_S0000442', 'I', 'POD0000007745'], dtype=object),
 array(['POD0000007750_S0000423', 'I', 'POD0000007750'], dtype=object),
 array(['POD0000007761_S0000068', 'I', 'POD0000007761'], dtype=object),
 array(['POD0000007771_S0000039', 'I', 'POD0000007771'], dtype=object),
 array(['POD0000007780_S0000505', 'I', 'POD0000007780'], dtype=object),
 array(['POD0000007785_S0000486', 'I', 'POD0000007785'], dtype=object),
 array(['POD0000007787_S0000186', 'I', 'POD0000007787'], dtype=object),
 array(['POD0000007798_S0000488', 'I', 'POD0000007798'], dtype=object),
 array(['POD0000007799_S0000383', 'I', 'POD0000007799'], dtype=object),
 array(['POD0000007801_S0000817', 'I', 'POD0000007801'], dtype=object),
 array(['POD0000008567_S0000203', 'I', 'POD0000008567'], dtype=object),
 array(['POD0000008579_S0000142', 'I', 'POD0000008579'], dtype=object),
 array(['POD0000008586_S0000139', 'I', 'POD0000008586'], dtype=object),
 array(['POD0000008637_S0000610', 'I', 'POD0000008637'], dtype=object),
 array(['POD0000008672_S0000121', 'I', 'POD0000008672'], dtype=object),
 array(['POD0000008685_S0000482', 'I', 'POD0000008685'], dtype=object),
 array(['POD0000008740_S0000236', 'I', 'POD0000008740'], dtype=object),
 array(['POD0000008751_S0000385', 'I', 'POD0000008751'], dtype=object),
 array(['POD0000008771_S0000327', 'I', 'POD0000008771'], dtype=object),
 array(['POD0000008789_S0000111', 'I', 'POD0000008789'], dtype=object),
 array(['POD0000008799_S0000079', 'A', 'POD0000008799'], dtype=object),
 array(['POD0000008861_S0000268', 'I', 'POD0000008861'], dtype=object),
 array(['POD0000008877_S0000301', 'I', 'POD0000008877'], dtype=object),
 array(['POD0000008879_S0000273', 'I', 'POD0000008879'], dtype=object),
 array(['POD0000008954_S0000469', 'I', 'POD0000008954'], dtype=object),
 array(['POD0000009068_S0000032', 'I', 'POD0000009068'], dtype=object),
 array(['POD0000009088_S0000258', 'I', 'POD0000009088'], dtype=object),

In [9]:
man_dict = manifest.to_dict('records')

In [14]:
man_dict[0]['transcript']

'DOUGLAS MCGRAY IS GOING TO BE OUR GUIDE YOU WALK THROUGH THE DOOR YOU SEE THE RED CARPETING YOU SEE SOMEONE IN A SUIT THEY MAY BE GREETING YOU '

In [10]:
%%timeit
sorted(man_dict, key=lambda d: len(d['transcript']) )

3.33 s ± 15.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]:
%%timeit
manifest.sort_values(by='transcript', key=lambda x: x.str.len(), inplace=False) # inplace = True returns None

8.63 s ± 89.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [14]:
manifest.wav_filename.to_numpy().nbytes  / 1e6

66.263904

In [40]:
manifest.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8282988 entries, 0 to 8282987
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   wav_filename  object
 1   wav_len       int64
 2   transcript    object
 3   speaker       object
dtypes: int64(1), object(3)
memory usage: 2.2 GB

Get runtime of each talker

In [47]:
manifest.groupby('speaker').wav_len.sum().sum()/1000 / 3600

9996.76101638889

In [31]:
segments = pd.read_csv(Path(path,'data', 'segments'), header=None, 
                       names=['wav_filename', 'speaker', 'start', 'end'], sep='\t')

In [49]:
segments.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8315357 entries, 0 to 8315356
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   wav_filename  object
 1   speaker       object
 2   start         float64
 3   end           float64
dtypes: float64(2), object(2)
memory usage: 1.3 GB

In [11]:
manifest.wav_filename

0       POD0000000001_S0000008
1       POD0000000001_S0000010
2       POD0000000001_S0000011
3       POD0000000001_S0000012
4       POD0000000001_S0000013
                 ...
9995    POD0000000077_S0000184
9996    POD0000000077_S0000185
9997    POD0000000077_S0000186
9998    POD0000000077_S0000187
9999    POD0000000078_S0000003
Name: wav_filename, Length: 10000, dtype: object

'1.3.5'

In [32]:
times = segments[['start', 'end']][segments.wav_filename.isin(manifest.wav_filename)]

In [66]:
times

            start       end
0          159.00    167.52
1          195.46    208.22
2          209.54    229.52
3          229.70    232.88
4          232.88    251.94
...           ...       ...
8282983  22068.70  22072.60
8282984  22072.60  22074.90
8282985  22074.90  22077.90
8282986  22077.90  22080.60
8282987  22080.60  22085.40

[8282987 rows x 2 columns]

In [33]:
df = pd.concat([manifest, times.set_index(manifest.index)], axis=1)

In [34]:
df.head(10)

,wav_filename,wav_len,transcript,speaker,start,end
0,POD0000000001_S0000008,8520,DOUGLAS MCGRAY IS GOING TO BE OUR GUIDE YOU WA...,POD0000000001,159.00,167.52
1,POD0000000001_S0000010,12759,AH ITALIAN AND AND THEN YOU HAVE A CONVERSATIO...,POD0000000001,195.46,208.22
2,POD0000000001_S0000011,19980,DOUG MCGRAY IS A JOURNALIST MY NAME IS DOUGLAS...,POD0000000001,209.54,229.52
3,POD0000000001_S0000012,3180,AH YOU LEAVE WITH CASH MINUS A THREE PERCENT F...,POD0000000001,229.70,232.88
4,POD0000000001_S0000013,19060,AND PAYDAY LENDING IS WHEN YOU DON'T HAVE ANY ...,POD0000000001,232.88,251.94
5,POD0000000001_S0000015,19740,WHAT MAY SURPRISE YOU THOUGH IF YOU HAVE THE S...,POD0000000001,257.77,277.51
6,POD0000000001_S0000016,7239,THE ABSENCE OF THE BANK-LIKE TRAPPINGS PLUSH C...,POD0000000001,277.60,284.84
7,POD0000000001_S0000017,7860,WHEN DOUG MCGRAY WENT OF A TOUR OF A BRANCH WI...,POD0000000001,285.05,292.91
8,POD0000000001_S0000018,5310,NIX POINTED OUT THE DESIGN CHOICES HE MADE YOU...,POD0000000001,293.00,298.31
9,POD0000000001_S0000019,9339,AND HE SAID YOU KNOW IF YOU GO INTO A BANK YOU...,POD0000000001,298.43,307.77

In [40]:
np_df = df.to_numpy()

In [48]:
np_df.nbytes / 1e6

397.583424

In [69]:
df.iloc[50]

wav_filename    POD0000000002_S0000046
wav_len                            810
transcript                    IT HAS A
speaker                  POD0000000002
start                           501.92
end                             502.73
Name: 50, dtype: object

In [32]:
df.transcript

0     DOUGLAS MCGRAY IS GOING TO BE OUR GUIDE YOU WA...
1     AH ITALIAN AND AND THEN YOU HAVE A CONVERSATIO...
2     DOUG MCGRAY IS A JOURNALIST MY NAME IS DOUGLAS...
3     AH YOU LEAVE WITH CASH MINUS A THREE PERCENT F...
4     AND PAYDAY LENDING IS WHEN YOU DON'T HAVE ANY ...
                            ...
95    SHE WAS VERY INTELLIGENT OF COURSE THEY HAD A ...
96    I KNOW I HAD KIND OF A FREAKY FEELING ABOUT TH...
97                                      OH THERE YOU GO
98    AS JANA AND I ARE TALKING AN ALARM STARTS GOIN...
99    WHEN ABO WAS BUILT IT GOT A FAIR AMOUNT OF MED...
Name: transcript, Length: 100, dtype: object

In [70]:
import os , sys 
sys.path.append('../src')

In [71]:
from text import load_text_encoder

In [72]:
tokenizer = load_text_encoder('word', '../tests/sample_data/gigaspeech_words-10k.vocab')

In [73]:
df['text'] = df['transcript'].apply(tokenizer.encode)

KeyboardInterrupt:

In [74]:
df = df.sort_values(by='transcript', key=lambda x: x.str.len(), inplace=False) # inplace = True returns None

In [114]:
eg = df.iloc[1000000]

In [115]:
eg

wav_filename    YOU0000008981_S0000245
wav_len                           1800
transcript          THEY BOTH CRUZ AND
speaker                  YOU0000008981
start                          1663.11
end                            1664.91
Name: 3970829, dtype: object

In [104]:
import torchaudio
from IPython.display import Audio

In [122]:
# demo get item logic:

speaker = eg.speaker
wav_path = wavscp.wav_path[wavscp.speaker == speaker].item()
start = int(eg.start * 16000 )
end = int(eg.end * 16000 )
num_frames = end - start 

audio, sr = torchaudio.load(wav_path, frame_offset=start, num_frames = num_frames)
audio = audio.numpy().squeeze()

In [123]:
eg.transcript

'THEY BOTH CRUZ AND'

In [124]:
Audio(audio, rate=sr)

In [103]:
eg.start, eg.end

(690.6, 691.35)

In [93]:
wav_path

'/rdma/vast-rdma/om3/data/public/GigaSpeech/audio/audiobook/P0003/AUD0000000202.wav'

In [ ]:
Audio(wavscp['POD0000000001'][1], rate = 16000)

In [33]:
eg_on = int(float(eg.start) * samp_rate)
eg_off = int(float(eg.end) * samp_rate) 

eg_wav = wavscp[eg.speaker][1][eg_on:eg_off]
print(eg.transcript)

DOUG MCGRAY IS A JOURNALIST MY NAME IS DOUGLAS MCGRAY I'M A FELLOW AT THE NEW AMERICAN FOUNDATION AND I AM THE EDITOR-IN-CHIEF OF POP-UP MAGAZINE AND A COUPLE OF YEARS AGO HE WROTE A STORY ABOUT CHECK CASHERS AND PAYDAY LENDERS WHICH MCGRAY IS QUICK TO POINT OUT THESE ARE DIFFERENT SERVICES CHECK CASHING IS WHEN YOU HAVE A CHECK IT'S MADE OUT TO YOU YOU GO IN WITH A CHECK YEAH

In [ ]:
Audio(eg_wav, rate = samp_rate)