In [80]:
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
import torch
import torchaudio 
import torchaudio.transforms as T

from datasets import load_dataset

import sys
sys.path.append('/om4/group/mcdermott/user/imgriff/projects/End-to-end-ASR-Pytorch/')
from corpus.single_word import SingleWordDataset as Dataset

In [7]:

path = '/om2/user/imgriff/projects/cocktail_party/datasets/GigaSpeech_top_200_words/' # Path to raw LibriSpeech dataset
dev_split = ['GigaSpeech_top_200_words']  # Name of data splits to be used as validation set

In [8]:
dataset = Dataset(path, dev_split, None, 1)

Using custom data configuration default-d77d8d0e2c068ac8
Reusing dataset csv (/home/imgriff/.cache/huggingface/datasets/csv/default-d77d8d0e2c068ac8/0.0.0/6b9057d9e23d9d8a2f05b985917a0da84d70c5dae3d22ddd8a3f22fb01c69d9e)

In [9]:
sampling_rate = 16000

In [12]:
processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

Downloading:   0%|          | 0.00/360M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

## Check performance on demo dataset

In [61]:
dataset2 = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation")
dataset2 = dataset2.sort("id")
sampling_rate = dataset2.features["audio"].sampling_rate

Downloading:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Downloading and preparing dataset librispeech_asr/clean to /home/imgriff/.cache/huggingface/datasets/hf-internal-testing___librispeech_asr/clean/2.1.0/d3bc4c2bc2078fcde3ad0f0f635862e4c0fef78ba94c4a34c4c250a097af240b...

  0%|          | 0/1 [00:00<?, ?it/s]

Downloading:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

  0%|          | 0/1 [00:00<?, ?it/s]

0 examples [00:00, ? examples/s]

Dataset librispeech_asr downloaded and prepared to /home/imgriff/.cache/huggingface/datasets/hf-internal-testing___librispeech_asr/clean/2.1.0/d3bc4c2bc2078fcde3ad0f0f635862e4c0fef78ba94c4a34c4c250a097af240b. Subsequent calls will reuse this data.

In [62]:
dataset2

Dataset({
    features: ['file', 'audio', 'text', 'speaker_id', 'chapter_id', 'id'],
    num_rows: 73
})

In [69]:
# results = []

model = model.cuda()
for ix in range(5):
    true = dataset2[ix]["text"]
    inputs = processor(dataset2[ix]["audio"]['array'], sampling_rate=sampling_rate, return_tensors="pt").to('cuda')
    with torch.no_grad():
        logits = model(**inputs).logits
    predicted_ids = torch.argmax(logits, dim=-1)

    # transcribe speech
    transcription = processor.batch_decode(predicted_ids)
    print(f'guess: {transcription[0]}')
    print(f'truth: {true}')
    print()
    
#     results.append({'hyp': transcription[0],
#                     'truth': true})

guess: MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL
truth: MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL

guess: NOR IS MISTER QUILTER'S MANNER LESS INTERESTING THAN HIS MATTER
truth: NOR IS MISTER QUILTER'S MANNER LESS INTERESTING THAN HIS MATTER

guess: HE TELLS US THAT AT THIS FESTIVE SEASON OF THE YEAR WITH CHRISTMANUS AND ROAST BEEF LOOMING BEFORE US SIMILES DRAWN FROM EATING AND ITS RESULTS OCCUR MOST READILY TO THE MIND
truth: HE TELLS US THAT AT THIS FESTIVE SEASON OF THE YEAR WITH CHRISTMAS AND ROAST BEEF LOOMING BEFORE US SIMILES DRAWN FROM EATING AND ITS RESULTS OCCUR MOST READILY TO THE MIND

guess: HE HAS GRAVED DOUBTS WHETHER SIR FREDERICK LAYTON'S WORK IS READY GREEK AFTER ALL AND CAN DISCOVER IN IT BUT LITTLE OF ROCKY ITHACA
truth: HE HAS GRAVE DOUBTS WHETHER SIR FREDERICK LEIGHTON'S WORK IS REALLY GREEK AFTER ALL AND CAN DISCOVER IN IT BUT LITTLE OF ROCKY ITHACA

guess: LINILL'S PICTURES ARE A SORT OF UP GUARDS AND ADAM PAINTINGS AND MASON'S EXQUISITE ITLS ARE AS NATIONAL AS A JINGO POEM MISTER BIRKATT FOSTERS LANDSCAPES SMILE AT ONE MUCH IN THE SAME WAY THAT MISTER CARKER USED TO FLASH HIS TEETH AND MISTER JOHN CAWLEYER GIVES HIS SITTER A CHEERFUL SLAP ON THE BACK BEFORE HE SAYS LIKE A CHAMPOOLER IN A TURKISH BATH NEXT MAN
truth: LINNELL'S PICTURES ARE A SORT OF UP GUARDS AND AT EM PAINTINGS AND MASON'S EXQUISITE IDYLLS ARE AS NATIONAL AS A JINGO POEM MISTER BIRKET FOSTER'S LANDSCAPES SMILE AT ONE MUCH IN THE SAME WAY THAT MISTER CARKER USED TO FLASH HIS TEETH AND MISTER JOHN COLLIER GIVES HIS SITTER A CHEERFUL SLAP ON THE BACK BEFORE HE SAYS LIKE A SHAMPOOER IN A TURKISH BATH NEXT MAN

We can see this is a character model based on the handful of errors made. Overall performance looks good.

## Check on Single Word Corpora

no language model is getting used, so things may be messy

In [70]:
dataset.dataset

Dataset({
    features: ['Unnamed: 0', 'word', 'wav_path'],
    num_rows: 200
})

In [81]:
resampler = T.Resample(44100, 16000, lowpass_filter_width=64,
                   rolloff=0.9475937167399596, 
                   resampling_method="kaiser_window",beta=14.769656459379492, dtype=torch.float32)

def load_audio(example):
    wav, sr = torchaudio.load(example['wav_path'])
    wav = resampler(wav)
    example['audio'] = wav
    example['sampling_rate'] = 16000
    return example

In [82]:
updated_dataset = dataset.dataset.map(load_audio)

0ex [00:00, ?ex/s]

In [83]:
updated_dataset[0]

{'Unnamed: 0': 0,
 'word': 'THE',
 'wav_path': '/om2/user/imgriff/projects/cocktail_party/datasets/GigaSpeech_top_200_words/The.wav',
 'audio': [[-1.0360400665376801e-05,
   -3.228379864594899e-05,
   -2.9783692298224196e-05,
   -3.093810300924815e-05,
   -3.0126482670311816e-05,
   -3.112291233264841e-05,
   -2.9290924430824816e-05,
   -5.418122236733325e-05,
   -6.27073532086797e-05,
   -6.0693666455335915e-05,
   -5.9715188399422914e-05,
   -7.302222365979105e-05,
   -9.539120947010815e-05,
   -8.93403121153824e-05,
   -9.276704804506153e-05,
   -0.00011355966125847772,
   -0.00012602814240381122,
   -0.00011839936632895842,
   -0.00012942183820996433,
   -0.00015273068856913596,
   -0.00015162889030762017,
   -0.00017005435074679554,
   -0.00018827164603862911,
   -0.00017799391935113817,
   -0.00020856880291830748,
   -0.0002118796546710655,
   -0.00022120244102552533,
   -0.00024273886810988188,
   -0.0002550320641603321,
   -0.00027793567278422415,
   -0.0002726104576140642,
   -0.00030047245672903955,
   -0.0003063501208089292,
   -0.00030500601860694587,
   -0.0003337074595037848,
   -0.000334462703904137,
   -0.0003464304027147591,
   -0.000370820052921772,
   -0.0003616100293584168,
   -0.0003825102758128196,
   -0.0003990523109678179,
   -0.00039461260894313455,
   -0.0004131916502956301,
   -0.00043555477168411016,
   -0.00045620871242135763,
   -0.00045897095697000623,
   -0.0004567401483654976,
   -0.0004585056158248335,
   -0.00045755162136629224,
   -0.0004566435527522117,
   -0.00047499965876340866,
   -0.0004924643435515463,
   -0.0004849355318583548,
   -0.0005095041706226766,
   -0.0005271937698125839,
   -0.0005288454121910036,
   -0.0005499701946973801,
   -0.000548527343198657,
   -0.0005822550738230348,
   -0.0005701158661395311,
   -0.0005774745950475335,
   -0.000572793825995177,
   -0.0005822651437483728,
   -0.0006046302733011544,
   -0.0005944176809862256,
   -0.0006340058753266931,
   -0.000639243284240365,
   -0.0006417999393306673,
   -0.0006401307182386518,
   -0.0006424065795727074,
   -0.0006220758077688515,
   -0.0006444878526963294,
   -0.0006378110265359282,
   -0.0006320551619865,
   -0.0006482501630671322,
   -0.0006331776967272162,
   -0.0006522279581986368,
   -0.0006636675680056214,
   -0.0006874853279441595,
   -0.0006826306344009936,
   -0.0006959697348065674,
   -0.0007029289845377207,
   -0.0006904928013682365,
   -0.0007119466317817569,
   -0.0007040033233352005,
   -0.0007003258215263486,
   -0.0007030168198980391,
   -0.0007112749735824764,
   -0.000730034604202956,
   -0.0007324267644435167,
   -0.0007322300225496292,
   -0.0007339383009821177,
   -0.0007175141363404691,
   -0.0007200195104815066,
   -0.0007411867845803499,
   -0.0007489637937396765,
   -0.0007616941002197564,
   -0.0007732508238404989,
   -0.0007631313055753708,
   -0.0007509032730013132,
   -0.000767568766605109,
   -0.0007981765083968639,
   -0.0008236716967076063,
   -0.0008231475949287415,
   -0.0008285008370876312,
   -0.0008447567815892398,
   -0.0008554584928788245,
   -0.0008538992842659354,
   -0.0008549890480935574,
   -0.0008778871851973236,
   -0.0008887779549695551,
   -0.0008799787028692663,
   -0.0008761646458879113,
   -0.0008889413438737392,
   -0.0009176961611956358,
   -0.0009116398287005723,
   -0.0009346513543277979,
   -0.0009715241030789912,
   -0.00100242393091321,
   -0.0010393410921096802,
   -0.0010345039190724492,
   -0.0010761343874037266,
   -0.0010588419390842319,
   -0.001051722327247262,
   -0.0010756829287856817,
   -0.001062141265720129,
   -0.0010736032854765654,
   -0.001062383409589529,
   -0.0010848522651940584,
   -0.001084862626157701,
   -0.0010758046992123127,
   -0.0010924551170319319,
   -0.0011216331040486693,
   -0.0011412163730710745,
   -0.0011258412851020694,
   -0.001137645449489355,
   -0.0011401507072150707,
   -0.001163044129498303,
   -0.0011445673881098628,
   -0.0011358715128153563,
   -0.0011756053427234292,
   -0.0011576976394280791,
   -0.0011758432956412435,
   -0.0012061881134286523,
   -0.0011974112130701542,
   -0.0011846072738990188,
   -0.0012055569095537066,
   -0.0012296534841880202,
   -0.0012315803905948997,
   -0.0012305239215493202,
   -0.0012306374264881015,
   -0.0012358761159703135,
   -0.0012397499522194266,
   -0.0012723739491775632,
   -0.0012776990188285708,
   -0.0012526654172688723,
   -0.001247358974069357,
   -0.0013052338035777211,
   -0.0013163916300982237,
   -0.0013038121396675706,
   -0.0013790912926197052,
   -0.0013617346994578838,
   -0.0013557643396779895,
   -0.001402015215717256,
   -0.0013825532514601946,
   -0.0014077193336561322,
   -0.0014495160430669785,
   -0.0014285114593803883,
   -0.0014506408479064703,
   -0.0014944927534088492,
   -0.0014723213389515877,
   -0.0014783759834244847,
   -0.0015006227185949683,
   -0.0014930283650755882,
   -0.0014682859182357788,
   -0.0014829159481450915,
   -0.00152584386523813,
   -0.0015123568009585142,
   -0.0015667228726670146,
   -0.0015948947984725237,
   -0.0015646825777366757,
   -0.00163990817964077,
   -0.0016662533162161708,
   -0.0016225897707045078,
   -0.0016690025804564357,
   -0.0017149337800219655,
   -0.0016902515199035406,
   -0.0017504814313724637,
   -0.0017260070890188217,
   -0.0017727293306961656,
   -0.0018405148293823004,
   -0.001792226918041706,
   -0.0018058974528685212,
   -0.001857746159657836,
   -0.0018843264551833272,
   -0.0017910036258399487,
   -0.0018588323146104813,
   -0.0018962864996865392,
   -0.0019008554518222809,
   -0.0019450627733021975,
   -0.0019543718080967665,
   -0.0019642726983875036,
   -0.0020035908091813326,
   -0.0020897442009299994,
   -0.002080464269965887,
   -0.0021353582851588726,
   -0.0021427730098366737,
   -0.0021208240650594234,
   -0.0020946962758898735,
   -0.0021584166679531336,
   -0.0021491970401257277,
   -0.0021605894435197115,
   -0.0022331795189529657,
   -0.0021569295786321163,
   -0.002249041572213173,
   -0.002175506204366684,
   -0.0022173379547894,
   -0.002224682830274105,
   -0.002076263539493084,
   -0.0021569624077528715,
   -0.002165444428101182,
   -0.0021022825967520475,
   -0.0021615298464894295,
   -0.0022922304924577475,
   -0.0022126149851828814,
   -0.0022178334183990955,
   -0.0022792613599449396,
   -0.002291566925123334,
   -0.0022926856763660908,
   -0.0021463793236762285,
   -0.0022477605380117893,
   -0.002236726460978389,
   -0.002077710349112749,
   -0.002209484577178955,
   -0.002138483338057995,
   -0.002088109962642193,
   -0.0021613920107483864,
   -0.0020767583046108484,
   -0.0020825047977268696,
   -0.0020132646895945072,
   -0.0019456639420241117,
   -0.0020235548727214336,
   -0.0018818859243765473,
   -0.001944754971191287,
   -0.0020416253246366978,
   -0.0018967237556353211,
   -0.0020482977852225304,
   -0.002002629917114973,
   -0.0019787754863500595,
   -0.0020232140086591244,
   -0.0020425277762115,
   -0.002108739921823144,
   -0.00206137471832335,
   -0.002114372095093131,
   -0.0021111106034368277,
   -0.0021705273538827896,
   -0.002156278118491173,
   -0.0021906686015427113,
   -0.0022020037285983562,
   -0.0021849623881280422,
   -0.002252485603094101,
   -0.002233900362625718,
   -0.002242186339572072,
   -0.002294567646458745,
   -0.002296212362125516,
   -0.0022700161207467318,
   -0.002334530232474208,
   -0.0023914340417832136,
   -0.002421449637040496,
   -0.0024213886354118586,
   -0.0024612247943878174,
   -0.0024578089360147715,
   -0.00245590484701097,
   -0.0024764402769505978,
   -0.002403268590569496,
   -0.002350341062992811,
   -0.002300386317074299,
   -0.0022872467525303364,
   -0.0022236336953938007,
   -0.0022298109252005816,
   -0.002247453900054097,
   -0.0022173442412167788,
   -0.0022829112131148577,
   -0.0022225002758204937,
   -0.0021808529272675514,
   -0.002205071272328496,
   -0.0022124177776277065,
   -0.0022698601242154837,
   -0.0023152318317443132,
   -0.0023247261997312307,
   -0.002400793135166168,
   -0.0023881997913122177,
   -0.0024111876264214516,
   -0.0024182682391256094,
   -0.002432978479191661,
   -0.0025215132627636194,
   -0.002526606200262904,
   -0.002644105814397335,
   -0.002664139261469245,
   -0.002610098570585251,
   -0.0026198236737400293,
   -0.002629297785460949,
   -0.002603011904284358,
   -0.00260261632502079,
   -0.0025510990526527166,
   -0.002531109843403101,
   -0.002545412164181471,
   -0.0025265247095376253,
   -0.002557954518124461,
   -0.002566117560490966,
   -0.0025766321923583746,
   -0.002569388598203659,
   -0.002609195886179805,
   -0.0026460750959813595,
   -0.002600658917799592,
   -0.002597118727862835,
   -0.0025960425846278667,
   -0.00255696102976799,
   -0.0025644763372838497,
   -0.0026116492226719856,
   -0.0025782622396945953,
   -0.0025198888033628464,
   -0.0025658144149929285,
   -0.0026152771897614002,
   -0.002653147792443633,
   -0.0026200120337307453,
   -0.0026852493174374104,
   -0.0027134595438838005,
   -0.0025393625255674124,
   -0.00260984362103045,
   -0.0025713364593684673,
   -0.0025203172117471695,
   -0.0025739616248756647,
   -0.0024779224768280983,
   -0.0025725068990141153,
   -0.0026106860022991896,
   -0.0025716230738908052,
   -0.0025330588687211275,
   -0.002512430539354682,
   -0.002535769948735833,
   -0.0025220776442438364,
   -0.0024575605057179928,
   -0.002372926799580455,
   -0.002489140024408698,
   -0.0024960834998637438,
   -0.002307900693267584,
   -0.0023348417598754168,
   -0.0023678531870245934,
   -0.0024100879672914743,
   -0.0024360395036637783,
   -0.0023631141521036625,
   -0.0025205491110682487,
   -0.002457935130223632,
   -0.002272759098559618,
   -0.002415045164525509,
   -0.0023033979814499617,
   -0.002326032379642129,
   -0.002422328805550933,
   -0.002192639745771885,
   -0.0023750916589051485,
   -0.0023839364293962717,
   -0.002172148320823908,
   -0.0022875398863106966,
   -0.0022803207393735647,
   -0.002222528913989663,
   -0.0022075013257563114,
   -0.0020982411224395037,
   -0.002237641951069236,
   -0.0022631827741861343,
   -0.002050407463684678,
   -0.0021786238066852093,
   -0.002269716700538993,
   -0.0023311416152864695,
   -0.0023508158046752214,
   -0.002265073824673891,
   -0.0024209534749388695,
   -0.002301342785358429,
   -0.0022483908105641603,
   -0.002429015003144741,
   -0.002319863298907876,
   -0.0023496460635215044,
   -0.0023878738284111023,
   -0.0022572812158614397,
   -0.002384001389145851,
   -0.0023779398761689663,
   -0.0022550022695213556,
   -0.002414961811155081,
   -0.0024004706647247076,
   -0.002383248880505562,
   -0.0024229532573372126,
   -0.0023860742803663015,
   -0.0024359370581805706,
   -0.0024803257547318935,
   -0.0024922580923885107,
   -0.002459824550896883,
   -0.0025096030440181494,
   -0.002552174963057041,
   -0.002431620378047228,
   -0.002355307573452592,
   -0.0023488302249461412,
   -0.002285368973389268,
   -0.002296904567629099,
   -0.0023646224290132523,
   -0.0023566423915326595,
   -0.0023674145340919495,
   -0.0023675267584621906,
   -0.0023707624059170485,
   -0.0023770418483763933,
   -0.0023599874693900347,
   -0.002338922582566738,
   -0.002347718458622694,
   -0.00233090459369123,
   -0.0022503037471324205,
   -0.0022770424839109182,
   -0.0022818995639681816,
   -0.002216063905507326,
   -0.00215729046612978,
   -0.0022001955658197403,
   -0.0021961070597171783,
   -0.0021019645500928164,
   -0.0021456372924149036,
   -0.0021445550955832005,
   -0.002157679758965969,
   -0.0021956991404294968,
   -0.002199110807850957,
   -0.0022715285886079073,
   -0.002275166567414999,
   -0.0022950805723667145,
   -0.002310772892087698,
   -0.00228255707770586,
   -0.0023732678964734077,
   -0.0023580361157655716,
   -0.002311608986929059,
   -0.0023294338025152683,
   -0.002299757907167077,
   -0.0022945478558540344,
   -0.0022528436966240406,
   -0.0021983981132507324,
   -0.0021900462452322245,
   -0.0022517701145261526,
   -0.002257615327835083,
   -0.0022046822123229504,
   -0.0022195186465978622,
   -0.0022333464585244656,
   -0.00225923303514719,
   -0.0022552702575922012,
   -0.002253785962238908,
   -0.002254282822832465,
   -0.002158297458663583,
   -0.0021470950450748205,
   -0.0021275077015161514,
   -0.0020860133226960897,
   -0.002099183388054371,
   -0.0021062225569039583,
   -0.0020824263337999582,
   -0.0020778984762728214,
   -0.002041653962805867,
   -0.0019533305894583464,
   -0.0019606647547334433,
   -0.001930752769112587,
   -0.0019568002317100763,
   -0.0019649022724479437,
   -0.0019632538314908743,
   -0.00196248316206038,
   -0.001896951231174171,
   -0.0019363192841410637,
   -0.001932200393639505,
   -0.0019069580594077706,
   -0.001936479238793254,
   -0.0018949502846226096,
   -0.0018893644446507096,
   -0.0018899381393566728,
   -0.0018409177428111434,
   -0.001847406500019133,
   -0.0018260173965245485,
   -0.0018023193115368485,
   -0.0018021339783445,
   -0.001808705274015665,
   -0.001829624525271356,
   -0.0018553565023466945,
   -0.0018076885025948286,
   -0.001802337123081088,
   -0.001806201646104455,
   -0.001791425165720284,
   -0.0018429512856528163,
   -0.0018733479082584381,
   -0.0018594579305499792,
   -0.001821950078010559,
   -0.0017989592161029577,
   -0.001856949762441218,
   -0.0018562782788649201,
   -0.0019119571661576629,
   -0.002006449270993471,
   -0.0018866051686927676,
   -0.0019684878643602133,
   -0.0020097007509320974,
   -0.001965862000361085,
   -0.001957553206011653,
   -0.0019312674412503839,
   -0.0020303118508309126,
   -0.001977518666535616,
   -0.002018027240410447,
   -0.0020913039334118366,
   -0.0020028792787343264,
   -0.0021023107692599297,
   -0.002069574547931552,
   -0.0020502402912825346,
   -0.002161606214940548,
   -0.0020489210728555918,
   -0.0020452141761779785,
   -0.0020231890957802534,
   -0.0019674396608024836,
   -0.0020737936720252037,
   -0.0020755541045218706,
   -0.0020535734947770834,
   -0.0020755818113684654,
   -0.002066631568595767,
   -0.002075043274089694,
   -0.0021147739607840776,
   -0.0021463476587086916,
   -0.0020809518173336983,
   -0.0020848866552114487,
   -0.0021410563495010138,
   -0.0020678588189184666,
   -0.0020859267096966505,
   -0.002139852149412036,
   -0.002072814619168639,
   -0.0020539434626698494,
   -0.0020867029670625925,
   -0.002086250577121973,
   -0.002026924164965749,
   -0.002031089970842004,
   -0.0020032264292240143,
   -0.001943869749084115,
   -0.0019488942343741655,
   -0.002020590240135789,
   -0.0020288622472435236,
   -0.0020014008041471243,
   -0.002026924164965749,
   -0.0019858854357153177,
   -0.002010272117331624,
   -0.0020730537362396717,
   -0.00206200429238379,
   -0.0020398637279868126,
   -0.0020564012229442596,
   -0.002001430606469512,
   -0.001958992565050721,
   -0.0019395137205719948,
   -0.0019421451725065708,
   -0.0019463665084913373,
   -0.0019553275778889656,
   -0.001900002360343933,
   -0.001928097801283002,
   -0.0019474686123430729,
   -0.0018218596233054996,
   -0.0018995548598468304,
   -0.0019333242671564221,
   -0.0018634451553225517,
   -0.0019217069493606687,
   -0.0019674187060445547,
   -0.0019248693715780973,
   -0.0019038013415411115,
   -0.0018408889882266521,
   -0.0019300364656373858,
   -0.0019675197545439005,
   -0.0019135024631395936,
   -0.0019832514226436615,
   -0.001963977236300707,
   -0.001960538327693939,
   -0.0019821447785943747,
   -0.0019355700351297855,
   -0.001902624499052763,
   -0.001940747955814004,
   -0.001959494547918439,
   -0.0019431972177699208,
   -0.001954432809725404,
   -0.00193258305080235,
   -0.0019341649021953344,
   -0.0019553396850824356,
   -0.0018709979485720396,
   -0.001908270874992013,
   -0.0019154397305101156,
   -0.001873051980510354,
   -0.0019992270972579718,
   -0.0019888966344296932,
   -0.0019119939533993602,
   -0.0019551480654627085,
   -0.001903690048493445,
   -0.001857692375779152,
   -0.001937640830874443,
   -0.0018857032991945744,
   -0.0018716203048825264,
   -0.0018756812205538154,
   -0.001792249851860106,
   -0.0018504711333662271,
   -0.001831721281632781,
   -0.0017396548064425588,
   -0.0017762510105967522,
   -0.00178391276858747,
   -0.0017831253353506327,
   -0.0018386055016890168,
   -0.0018028721679002047,
   -0.0017637989949434996,
   -0.001804536790587008,
   -0.001768210669979453,
   -0.0017569552874192595,
   -0.001793592469766736,
   -0.0018046952318400145,
   -0.0017733045388013124,
   -0.00179642578586936,
   -0.0018434039084240794,
   -0.0018021814757958055,
   -0.0018259885255247355,
   -0.001810839748941362,
   -0.0017517308006063104,
   -0.0017798697808757424,
   -0.0017792643047869205,
   -0.0018361005932092667,
   -0.0018984571797773242,
   -0.0018382066627964377,
   -0.0018302814569324255,
   -0.0018242236692458391,
   -0.0018620312912389636,
   -0.0018915657419711351,
   -0.0018672128207981586,
   -0.0019089923007413745,
   -0.0019358936697244644,
   -0.0019202845869585872,
   -0.0019237446831539273,
   -0.0019212234765291214,
   -0.0019348227651789784,
   -0.0019543874077498913,
   -0.0019196124048903584,
   -0.0018466858891770244,
   -0.001763913780450821,
   -0.0017821843503043056,
   -0.001705064089037478,
   -0.0016548782587051392,
   -0.0017035037744790316,
   -0.0016781882150098681,
   -0.0016834657872095704,
   -0.0017006795387715101,
   -0.0017013843171298504,
   -0.0016707604518160224,
   -0.0016613744664937258,
   -0.0016134853940457106,
   -0.001534468145109713,
   -0.001588042825460434,
   -0.0015639396151527762,
   -0.0015196808381006122,
   -0.0016177973011508584,
   -0.0015435811365023255,
   -0.0015066830674186349,
   -0.0015196799067780375,
   -0.0015209967968985438,
   -0.0015607953537255526,
   -0.0015553010161966085,
   -0.0015549713280051947,
   -0.0015910729998722672,
   -0.0016330642392858863,
   -0.0016148771392181516,
   -0.0016662942944094539,
   -0.001721802749671042,
   -0.0017701903125271201,
   -0.0017804022645577788,
   -0.0017695797141641378,
   -0.0018325429409742355,
   -0.0018709572032094002,
   -0.001903328811749816,
   -0.0020167450420558453,
   -0.0021491488441824913,
   -0.0021237286273390055,
   -0.002162701217457652,
   -0.0022394342813640833,
   -0.0021641443017870188,
   -0.002253901679068804,
   -0.0023051779717206955,
   -0.0022697898093611,
   -0.0023027914576232433,
   -0.002367426175624132,
   -0.0023803405929356813,
   -0.002435744507238269,
   -0.002476172987371683,
   -0.0023757435847073793,
   -0.002391199581325054,
   -0.0024021193385124207,
   -0.002384230261668563,
   -0.002414151094853878,
   -0.0024509187787771225,
   -0.002479713410139084,
   -0.0025161036755889654,
   -0.0024806023575365543,
   -0.0025112226139754057,
   -0.002573765115812421,
   -0.0024659037590026855,
   -0.0024116849526762962,
   -0.0024664064403623343,
   -0.002460276475176215,
   -0.0024740213993936777,
   -0.002535337582230568,
   -0.0024752365425229073,
   -0.0024413305800408125,
   -0.002379467012360692,
   -0.0023149619810283184,
   -0.002284341724589467,
   -0.002230384387075901,
   -0.002212231047451496,
   -0.0021704279351979494,
   -0.0021104656625539064,
   -0.0021019389387220144,
   -0.0020650923252105713,
   -0.0019716909155249596,
   -0.0019819685257971287,
   -0.0018814760260283947,
   -0.0018114731647074223,
   -0.0017845173133537173,
   -0.001686840201728046,
   -0.0016253486974164844,
   -0.0015963469631969929,
   -0.0015294424956664443,
   -0.001507495529949665,
   -0.001504251966252923,
   -0.0014723832719027996,
   -0.0014316580491140485,
   -0.001315169152803719,
   -0.001389955752529204,
   -0.0013026859378442168,
   -0.0012300991220399737,
   -0.0013264318695291877,
   -0.001203695428557694,
   -0.0011759030167013407,
   -0.0011982726864516735,
   -0.001102539710700512,
   -0.0011215429985895753,
   -0.0011549497721716762,
   -0.0011045682476833463,
   -0.0011135353706777096,
   -0.0011357525363564491,
   -0.001186930574476719,
   -0.0011543696746230125,
   -0.0011444768169894814,
   -0.0012038907734677196,
   -0.0011720338370651007,

In [84]:
results = []

model = model.cuda()
for sample in updated_dataset:
    true = sample["word"]
    inputs = processor(sample["audio"], sampling_rate=sampling_rate, return_tensors="pt").to('cuda')
    with torch.no_grad():
        logits = model(**inputs).logits
    predicted_ids = torch.argmax(logits, dim=-1)

    # transcribe speech
    transcription = processor.batch_decode(predicted_ids)
    print(f'guess: {transcription[0]}')
    print(f'truth: {true}')
    print()
    
    results.append({'hyp': transcription[0],
                    'truth': true})

guess: THE
truth: THE

guess: AND
truth: AND

guess: TWO
truth: TO

guess: OF
truth: OF

guess: A
truth: A

guess: THAT
truth: THAT

guess: IN
truth: IN

guess: I
truth: I

guess: YOU
truth: YOU

guess: IS
truth: IS

guess: IT
truth: IT

guess: WAS
truth: WAS

guess: FOUR
truth: FOR

guess: SO
truth: SO

guess: THIS
truth: THIS

guess: WE
truth: WE

guess: BUT
truth: BUT

guess: WITH
truth: WITH

guess: ON
truth: ON

guess: HAVE
truth: HAVE

guess: HE
truth: HE

guess: AS
truth: AS

guess: B
truth: BE

guess: R
truth: ARE

guess: THEY
truth: THEY

guess: NOT
truth: NOT

guess: AT
truth: AT

guess: LIKE
truth: LIKE

guess: WHAT
truth: WHAT

guess: NO
truth: KNOW

guess: HIS
truth: HIS

guess: ALL
truth: ALL

guess: ABOUT
truth: ABOUT

guess: ONE
truth: ONE

guess: MORE
truth: OR

guess: HAD
truth: HAD

guess: IF
truth: IF

guess: MY
truth: MY

guess: DE
truth: DO

guess: FROM
truth: FROM

guess: THERE
truth: THERE

guess: JUST
truth: JUST

guess: CAN
truth: CAN

guess: YOUR
truth: YOUR

guess: BY
truth: BY

guess: AH
truth: AH

guess: ME
truth: ME

guess: ANN
truth: AN

guess: WHEN
truth: WHEN

guess: WAR
truth: WERE

guess: PEOPLE
truth: PEOPLE

guess: WHICH
truth: WHICH

guess: HER
truth: HER

guess: SHE
truth: SHE

guess: OUT
truth: OUT

guess: THINK
truth: THINK

guess: WOULD
truth: WOULD

guess: UP
truth: UP

guess: THEN
truth: THEN

guess: HOUR
truth: OUR

guess: WHO
truth: WHO

guess: THERE
truth: THEIR

guess: THEM
truth: THEM

guess: MORE
truth: MORE

guess: NOW
truth: NOW

guess: SOME
truth: SOME

guess: HOW
truth: HOW

guess: VERY
truth: VERY

guess: BECAUSE
truth: BECAUSE

guess: WILL
truth: WILL

guess: BEN
truth: BEEN

guess: UM
truth: UM

guess: GOING
truth: GOING

guess: REALLY
truth: REALLY

guess: NO
truth: NO

guess: TIME
truth: TIME

guess: HAS
truth: HAS

guess: HIM
truth: HIM

guess: GET
truth: GET

guess: THESE
truth: THESE

guess: SAID
truth: SAID

guess: INTWO
truth: INTO

guess: RIGHT
truth: RIGHT

guess: HERE
truth: HERE

guess: GO
truth: GO

guess: OTHER
truth: OTHER

guess: WELL
truth: WELL

guess: SEA
truth: SEE

guess: TWO
truth: TWO

guess: COULD
truth: COULD

guess: WHERE
truth: WHERE

guess: WAY
truth: WAY

guess: US
truth: US

guess: ALSO
truth: ALSO

guess: THOSE
truth: THOSE

guess: WONT
truth: WANT

guess: SAY
truth: SAY

guess: THINGS
truth: THINGS

guess: YERE
truth: YEAH

guess: DID
truth: DID

guess: MUCH
truth: MUCH

guess: BACK
truth: BACK

guess: FIRST
truth: FIRST

guess: MACKE
truth: MAKE

guess: OVER
truth: OVER

guess: THEN
truth: THAN

guess: GOOD
truth: GOOD

guess: LITTLE
truth: LITTLE

guess: ANY
truth: ANY

guess: KIND
truth: KIND

guess: SOMETHING
truth: SOMETHING

guess: EVEN
truth: EVEN

guess: ONLY
truth: ONLY

guess: LOT
truth: LOT

guess: NO
truth: NEW

guess: GOT
truth: GOT

guess: DOWN
truth: DOWN

guess: THING
truth: THING

guess: BEING
truth: BEING

guess: ACTUALLY
truth: ACTUALLY

guess: WORK
truth: WORK

guess: COME
truth: COME

guess: THROUGH
truth: THROUGH

guess: MANY
truth: MANY

guess: LOOK
truth: LOOK

guess: TAKE
truth: TAKE

guess: MOST
truth: MOST

guess: YEARS
truth: YEARS

guess: BEFOUR
truth: BEFORE

guess: AFTER
truth: AFTER

guess: SHOULD
truth: SHOULD

guess: GREAT
truth: GREAT

guess: NEED
truth: NEED

guess: THREE
truth: THREE

guess: WHY
truth: WHY

guess: AGAIN
truth: AGAIN

guess: LIFE
truth: LIFE

guess: WORLD
truth: WORLD

guess: DAY
truth: DAY

guess: MAD
truth: MADE

guess: MIGHT
truth: MIGHT

guess: DIFFERENT
truth: DIFFERENT

guess: IT'S
truth: ITS

guess: MAN
truth: MAN

guess: EVERY
truth: EVERY

guess: NEVER
truth: NEVER

guess: STILL
truth: STILL

guess: MEAN
truth: MEAN

guess: OWN
truth: OWN

guess: TWO
truth: TOO

guess: SAME
truth: SAME

guess: USE
truth: USE

guess: DOING
truth: DOING

guess: MAY
truth: MAY

guess: PUT
truth: PUT

guess: AROUND
truth: AROUND

guess: LAST
truth: LAST

guess: PART
truth: PART

guess: CAME
truth: CAME

guess: ANOTHER
truth: ANOTHER

guess: LONG
truth: LONG

guess: OFF
truth: OFF

guess: FIVE
truth: FIVE

guess: SUCH
truth: SUCH

guess: FIND
truth: FIND

guess: ALWAYS
truth: ALWAYS

guess: DOES
truth: DOES

guess: THANK
truth: THANK

guess: NEXT
truth: NEXT

guess: YES
truth: YES

guess: POINT
truth: POINT

guess: GIVE
truth: GIVE

guess: SORT
truth: SORT

guess: TELL
truth: TELL

guess: WHEN
truth: WENT

guess: TALK
truth: TALK

guess: LOVE
truth: LOVE

guess: THOUGHT
truth: THOUGHT

guess: OLD
truth: OLD

guess: PLACE
truth: PLACE

guess: AM
truth: AM

guess: OH
truth: OH

guess: YEAR
truth: YEAR

guess: SHOW
truth: SHOW

guess: CALLED
truth: CALLED

guess: DONE
truth: DONE

guess: AWAY
truth: AWAY

guess: FOUR
truth: FOUR

guess: QUESTION
truth: QUESTION

guess: FEEL
truth: FEEL

guess: COURSE
truth: COURSE

guess: BETTER
truth: BETTER

guess: O Q
truth: OKAY

guess: WHILE
truth: WHILE

guess: BIG
truth: BIG

guess: TWENTY
truth: TWENTY

guess: EACH
truth: EACH

guess: SURE
truth: SURE

guess: HOLETE
truth: LET

guess: GUNNER
truth: GONNA

tensor([[-0.0008, -0.0046, -0.0041,  ...,  0.0008,  0.0008,  0.0008]],
       device='cuda:0')

In [85]:
import pandas as pd

In [86]:
results = pd.DataFrame(results)

In [87]:
results.head(50)

      hyp  truth
0     THE    THE
1     AND    AND
2     TWO     TO
3      OF     OF
4       A      A
5    THAT   THAT
6      IN     IN
7       I      I
8     YOU    YOU
9      IS     IS
10     IT     IT
11    WAS    WAS
12   FOUR    FOR
13     SO     SO
14   THIS   THIS
15     WE     WE
16    BUT    BUT
17   WITH   WITH
18     ON     ON
19   HAVE   HAVE
20     HE     HE
21     AS     AS
22      B     BE
23      R    ARE
24   THEY   THEY
25    NOT    NOT
26     AT     AT
27   LIKE   LIKE
28   WHAT   WHAT
29     NO   KNOW
30    HIS    HIS
31    ALL    ALL
32  ABOUT  ABOUT
33    ONE    ONE
34   MORE     OR
35    HAD    HAD
36     IF     IF
37     MY     MY
38     DE     DO
39   FROM   FROM
40  THERE  THERE
41   JUST   JUST
42    CAN    CAN
43   YOUR   YOUR
44     BY     BY
45     AH     AH
46     ME     ME
47    ANN     AN
48   WHEN   WHEN
49    WAR   WERE

In [92]:
top_match_guesses = results[(results['hyp'] == results['truth'])]
percent_right = 100 * len(top_match_guesses) / len(results.truth.unique())
print(f"{len(top_match_guesses)} matched guesses; {round(percent_right,2)}% correct")
top_match_guesses

173 matched guesses; 86.5% correct

        hyp   truth
0       THE     THE
1       AND     AND
3        OF      OF
4         A       A
5      THAT    THAT
..      ...     ...
193   WHILE   WHILE
194     BIG     BIG
195  TWENTY  TWENTY
196    EACH    EACH
197    SURE    SURE

[173 rows x 2 columns]