In [1]:
import pandas as pd
import os 
from pathlib import Path
import numpy as np
%matplotlib inline 
import matplotlib.pyplot as plt 
from matplotlib import cm

In [2]:
ccc_path = '/om2/user/imgriff/projects/cocktail_party/datasets/EnglishCCC_v1.2'

In [3]:
ccc_df = pd.read_csv(Path(ccc_path, "confusionCorpus_v1.2.csv"))

In [5]:
from IPython.display import Audio

In [9]:
path_to_ECCC = '/om2/user/imgriff/projects/cocktail_party/datasets/EnglishCCC_v1.2/confusionWavs/'

In [11]:
make_path = lambda ID: Path(path_to_ECCC, f"T_{ID}.wav").as_posix()

ccc_df['wav_path'] = ccc_df['ID'].apply(make_path)

<ipython-input-11-643ebc0a64f3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wanted_df['wav_path'] = wanted_df['ID'].apply(make_path)

In [15]:
ccc_df.head(10)

,ID,Length,Masker,Onset,SNR,Speaker,Target,Raw,Responses,N-Listeners,...,Confusion,Consistency,Target-Arpabet,Target-IPA,Target-frequency,Confusion-Arpabet,Confusion-IPA,Confusion-frequency,Phoneme-distance,wav_path
0,3784,11520,SSN,104656,-6.982,s3,jointly,drink|drink|drink|drinking|dream|jointly|join|...,drink|jointly|join|enjoyment|drinking|dream,15,...,drink,9,! JH OY N T . L IY,! dʒ ɔɪ n t . l i,3.10,! D R IH NG K,! d ɹ ɪ ŋ k,5.06,57,/om2/user/imgriff/projects/cocktail_party/data...
1,3786,9172,SSN,455143,-6.173,s3,buyer,fire|buyer|fire|fire|pie|fire|fire|quiet|fire|...,fire|buyer|quiet|pie|prior|final,15,...,fire,9,! B AY . AX,! b aɪ . ə,4.13,! F AY . AX,! f aɪ . ə,5.18,10,/om2/user/imgriff/projects/cocktail_party/data...
2,3787,13280,SSN,658770,-6.200,s3,sleek,sleek|sleep|sleep|sleek|sleep|sleek|sleep|slee...,sleep|sleek,15,...,sleep,10,! S L IY K,! s l i k,3.29,! S L IY P,! s l i p,4.94,10,/om2/user/imgriff/projects/cocktail_party/data...
3,3791,14898,SSN,826266,-5.132,s3,perverse,perverse|averse|traverse|reverse|reverse|perve...,reverse|perverse|averse|traverse,15,...,reverse,8,P AX ! V ER S,p ə ! v ɜ s,3.13,R AX ! V ER S,ɹ ə ! v ɜ s,4.15,20,/om2/user/imgriff/projects/cocktail_party/data...
4,3804,11876,SSN,496159,-5.623,s3,because,curse|because|coat|coast|reverse|coast|coast|c...,coast|coat|because|curse|reverse,15,...,coast,8,B IH ! K OH Z,b ɪ ! k ɒ z,6.22,! K OW S T,! k oʊ s t,4.86,41,/om2/user/imgriff/projects/cocktail_party/data...
5,3805,12960,SSN,102704,-6.534,s3,remote,remember|remember|remote|remote|women|flamingo...,remember|remote|woman|remembered|flamingo|women,15,...,remember,7,R IH ! M OW T,ɹ ɪ ! m oʊ t,4.32,R IH ! M EH M . B AX,ɹ ɪ ! m e m . b ə,5.52,34,/om2/user/imgriff/projects/cocktail_party/data...
6,3848,10818,BAB4,521819,-2.165,s3,barber,harbour|arbour|barbaric|harder|reports|harbour...,harbour|arbour|harder|reports|barbaric|barber|...,14,...,harbour,6,! B AA . B AX,! b ɑ . b ə,3.63,! HH AA . B AX,! h ɑ . b ə,4.12,10,/om2/user/imgriff/projects/cocktail_party/data...
7,3884,9440,BMN3,281850,-3.348,s2,childish,children|children|children|choir|children|chil...,children|choir,15,...,children,14,! CH AY L . D IH SH,! tʃ aɪ l . d ɪ ʃ,3.42,! CH IH L . D R AX N,! tʃ ɪ l . d ɹ ə n,5.53,37,/om2/user/imgriff/projects/cocktail_party/data...
8,3891,11680,BMN3,787862,-7.670,s2,radius,radio|gradient|radio|radius|radiant|radio|raid...,radio|radius|rating|rabies|gradient|radiant|ra...,15,...,radio,7,! R EY . D IA S,! ɹ eɪ . d ɪə s,3.33,! R EY . D IY . OW,! ɹ eɪ . d i . oʊ,4.82,20,/om2/user/imgriff/projects/cocktail_party/data...
9,3892,13280,BMN3,856391,-7.311,s2,stance,stars|stance|stars|stars|staff|stance|stars|st...,stars|stance|sparse|start|scarce|staff,15,...,stars,7,! S T AA N S,! s t ɑ n s,3.74,! S T AA Z,! s t ɑ z,4.80,17,/om2/user/imgriff/projects/cocktail_party/data...

In [16]:
Audio(ccc_df['wav_path'][4])

In [13]:
wanted_df = ccc_df[['ID', 'Target']]
wanted_df['wav_path'] = wanted_df['ID'].apply(make_path)

<ipython-input-13-7085ed2a2670>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wanted_df['wav_path'] = wanted_df['ID'].apply(make_path)

In [14]:
wanted_df

         ID     Target                                           wav_path
0      3784    jointly  /om2/user/imgriff/projects/cocktail_party/data...
1      3786      buyer  /om2/user/imgriff/projects/cocktail_party/data...
2      3787      sleek  /om2/user/imgriff/projects/cocktail_party/data...
3      3791   perverse  /om2/user/imgriff/projects/cocktail_party/data...
4      3804    because  /om2/user/imgriff/projects/cocktail_party/data...
...     ...        ...                                                ...
3202  43714       dose  /om2/user/imgriff/projects/cocktail_party/data...
3203  43715  fifteenth  /om2/user/imgriff/projects/cocktail_party/data...
3204  43726   presence  /om2/user/imgriff/projects/cocktail_party/data...
3205  43788     output  /om2/user/imgriff/projects/cocktail_party/data...
3206  43873      shelf  /om2/user/imgriff/projects/cocktail_party/data...

[3207 rows x 3 columns]

In [23]:
wanted_df.wav_path[0], wanted_df.Target[0],

('/om2/user/imgriff/projects/cocktail_party/datasets/EnglishCCC_v1.2/confusionWavs/T_3784.wav',
 'jointly')

In [46]:
out_df = wanted_df[['wav_path', 'Target']]

In [47]:
out_df['word'] = out_df['Target'].str.upper()

In [48]:
out_df = out_df[['wav_path', 'word']]

In [49]:
out_df

                                               wav_path       word
0     /om2/user/imgriff/projects/cocktail_party/data...    JOINTLY
1     /om2/user/imgriff/projects/cocktail_party/data...      BUYER
2     /om2/user/imgriff/projects/cocktail_party/data...      SLEEK
3     /om2/user/imgriff/projects/cocktail_party/data...   PERVERSE
4     /om2/user/imgriff/projects/cocktail_party/data...    BECAUSE
...                                                 ...        ...
3202  /om2/user/imgriff/projects/cocktail_party/data...       DOSE
3203  /om2/user/imgriff/projects/cocktail_party/data...  FIFTEENTH
3204  /om2/user/imgriff/projects/cocktail_party/data...   PRESENCE
3205  /om2/user/imgriff/projects/cocktail_party/data...     OUTPUT
3206  /om2/user/imgriff/projects/cocktail_party/data...      SHELF

[3207 rows x 2 columns]

In [50]:
out_path = Path(ccc_path, 'EnglishConsistentConfusionCorpus_words.csv')
# out_df.to_csv(out_path)