In [1]:
import numpy as np 
import pandas as pd 
from pathlib import Path

## Need to make sure test stimuli are have valid cues associated with each target

In [132]:
bad_talker_names = ['wikipedia', 'viktor-o-ledenyov',  'acerperi', 'bowie-media', '1904-cc' ]

In [2]:
swc_human_stim_path = Path('/om/user/imgriff/datasets/human_word_rec_SWC_2023')

In [23]:
swc_human_stim_path = Path('/om/user/imgriff/datasets/human_word_rec_SWC_2023')
full_swc_manifest = pd.read_pickle('/om2/user/imgriff/datasets/spatial_audio_pipeline/assets/human_attn_experiment_v00/full_eval_trial_manifest_new_fnames_w_transcripts.pdpkl')
full_swc_manifest

,distractor_client_id,distractor_clip_dur_in_s,distractor_clip_end_in_s,distractor_clip_start_in_s,distractor_corpus,distractor_gender,distractor_gender_int,distractor_split,distractor_split_int,distractor_sr,...,cue_word,cue_src_ix,cue_client_id,cue_src_fn,cue_clip_start_in_s,cue_clip_end_in_s,gender_cond_td,cue_clip_dur_in_s,target_transcripts,distractor_transcripts
0,popularoutcast,0.44,359.92,359.48,swc,female,0,NaN,0,44100,...,dramatic,992746,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1147.51,1147.96,female_female,0.45,"[however, the, cost, for, these, new, types, o...","[made, from, either, dna, or]"
1,matthewdgonzalez,0.49,584.65,584.16,swc,male,1,NaN,0,44100,...,dramatic,992746,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1147.51,1147.96,female_male,0.45,"[however, the, cost, for, these, new, types, o...","[in, one thousand, nine hundred and forty, sev..."
2,flyingtoaster,0.17,1711.42,1711.25,swc,female,0,NaN,0,44100,...,allows,992957,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1905.81,1906.30,female_female,0.49,"[so, that, they, can, simply, load, in, the, c...","[of, the, core, rule, books, were, slightly, r..."
3,warmvoiceover,0.76,487.07,486.31,swc,male,1,NaN,0,44100,...,allows,992957,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1905.81,1906.30,female_male,0.49,"[so, that, they, can, simply, load, in, the, c...","[philadelphia, created, in, seventeen]"
4,popularoutcast,0.56,432.21,431.65,swc,female,0,NaN,0,44100,...,with,999423,99of9-toby-hudson,/om/user/imgriff/datasets/spatial_audio_pipeli...,642.92,643.09,male_female,0.17,"[resulted, in, the, death, due, to, a, gas, leak]","[this, was, a, then, unknown, fault]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,matthewdgonzalez,0.64,1951.59,1950.95,swc,male,1,NaN,0,44100,...,what,98511,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,220.31,220.61,male_male,0.30,"[and, hurricane, force, wins]","[and, frequently, analyzed]"
1436,popularoutcast,0.62,552.97,552.35,swc,female,0,NaN,0,44100,...,actor,99323,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,6.37,6.68,male_female,0.31,"[bed, chief, wiggum, charging]","[much, earlier]"
1437,incledon,0.49,494.41,493.92,swc,male,1,NaN,0,44100,...,actor,99323,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,6.37,6.68,male_male,0.31,"[bed, chief, wiggum, charging]","[and, south, africa]"
1438,popularoutcast,0.62,956.40,955.78,swc,female,0,NaN,0,44100,...,into,563727,zegoma-beach,/om/user/imgriff/datasets/spatial_audio_pipeli...,213.10,213.29,male_female,0.19,"[is, played, in, the, attack]","[browser, for, windows, mac]"
1439,jdhowens90,0.58,1929.91,1929.33,swc,male,1,NaN,0,44100,...,into,563727,zegoma-beach,/om/user/imgriff/datasets/spatial_audio_pipeli...,213.10,213.29,male_male,0.19,"[is, played, in, the, attack]","[of, the, nazi, germany, which, was, a]"

In [24]:
bad_talker_df = full_swc_manifest[full_swc_manifest['client_id'].isin(bad_talker_names)]

In [25]:
bad_talker_df

,distractor_client_id,distractor_clip_dur_in_s,distractor_clip_end_in_s,distractor_clip_start_in_s,distractor_corpus,distractor_gender,distractor_gender_int,distractor_split,distractor_split_int,distractor_sr,...,cue_word,cue_src_ix,cue_client_id,cue_src_fn,cue_clip_start_in_s,cue_clip_end_in_s,gender_cond_td,cue_clip_dur_in_s,target_transcripts,distractor_transcripts
0,popularoutcast,0.44,359.92,359.48,swc,female,0,NaN,0,44100,...,dramatic,992746,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1147.51,1147.96,female_female,0.45,"[however, the, cost, for, these, new, types, o...","[made, from, either, dna, or]"
1,matthewdgonzalez,0.49,584.65,584.16,swc,male,1,NaN,0,44100,...,dramatic,992746,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1147.51,1147.96,female_male,0.45,"[however, the, cost, for, these, new, types, o...","[in, one thousand, nine hundred and forty, sev..."
2,flyingtoaster,0.17,1711.42,1711.25,swc,female,0,NaN,0,44100,...,allows,992957,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1905.81,1906.30,female_female,0.49,"[so, that, they, can, simply, load, in, the, c...","[of, the, core, rule, books, were, slightly, r..."
3,warmvoiceover,0.76,487.07,486.31,swc,male,1,NaN,0,44100,...,allows,992957,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1905.81,1906.30,female_male,0.49,"[so, that, they, can, simply, load, in, the, c...","[philadelphia, created, in, seventeen]"
20,persian-poet-gal,0.20,524.68,524.48,swc,female,0,NaN,0,44100,...,movements,998947,acerperi,/om/user/imgriff/datasets/spatial_audio_pipeli...,118.71,119.18,female_female,0.47,"[hushscaled, vocal, music, creation]","[wealth, could, reward, hard, work]"
21,rybupsp,0.01,587.76,587.75,swc,male,1,NaN,0,44100,...,movements,998947,acerperi,/om/user/imgriff/datasets/spatial_audio_pipeli...,118.71,119.18,female_male,0.47,"[hushscaled, vocal, music, creation]","[huge, numbers, of, birds, and, animals, from]"
116,popularoutcast,0.22,323.76,323.54,swc,female,0,NaN,0,44100,...,picture,537111,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,410.32,410.69,female_female,0.37,"[and, immediately, began, landing]","[believes, on, a, white, field]"
117,viktor-o-ledenyov,0.42,42.35,41.93,swc,male,1,NaN,0,44100,...,picture,537111,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,410.32,410.69,female_male,0.37,"[and, immediately, began, landing]","[institutions, like, international, monetary, ..."
118,persian-poet-gal,0.90,138.51,137.61,swc,female,0,NaN,0,44100,...,soon,536921,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,116.36,116.69,female_female,0.33,"[during, home, games, at, the, staples]","[prestigious, international, football]"
119,beno1000,0.08,129.68,129.60,swc,male,1,NaN,0,44100,...,soon,536921,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,116.36,116.69,female_male,0.33,"[during, home, games, at, the, staples]","[examples, of, the, types, of, animal, cow]"
120,laurahale,0.38,1.31,0.93,swc,female,0,NaN,0,44100,...,from,537357,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,212.71,212.88,female_female,0.17,"[and, then, the, final, line, of, the, circle]","[united, states, mens, national]"
121,karltalk,0.40,37.16,36.76,swc,male,1,NaN,0,44100,...,from,537357,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,212.71,212.88,female_male,0.17,"[and, then, the, final, line, of, the, circle]","[plot, features, james, t, kirk]"
122,popularoutcast,0.42,949.83,949.41,swc,female,0,NaN,0,44100,...,bassist,537348,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,206.27,207.05,female_female,0.78,"[although, they, never, actually, did]","[estimated, to, be, about, one thousand]"
123,enviroboy,0.63,459.95,459.32,swc,male,1,NaN,0,44100,...,bassist,537348,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,206.27,207.05,female_male,0.78,"[although, they, never, actually, did]","[they, continue, quote]"
124,eleaverton,0.41,170.02,169.61,swc,female,0,NaN,0,44100,...,girl,536821,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,84.64,85.16,female_female,0.52,"[and, musical, influences]","[would, have, made, a, number, of, mass, transit]"
125,the-voice-of-hassocks,0.33,4285.41,4285.08,swc,male,1,NaN,0,44100,...,girl,536821,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,84.64,85.16,female_male,0.52,"[and, musical, influences]","[compared, to, twenty, four, middle, class]"
126,sedola,0.36,1826.98,1826.62,swc,female,0,NaN,0,44100,...,film,537240,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,112.60,113.15,female_female,0.55,"[is, featured, on, the, lifehackcom]","[agreement, with, the, city, college, of, new,..."
127,vonfraginoff,0.38,657.82,657.44,swc,male,1,NaN,0,44100,...,film,537240,bowie-media,/om/user/imgriff/datasets/spatial_audio_pipeli...,112.60,113.15,female_male,0.55,"[is, featured, on, the, lifehackcom]","[allowing, it, to, defeat, the, soviet, union,..."
1354,popularoutcast,0.38,871.09,870.71,swc,female,0,NaN,0,44100,...,income,377497,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,830.05,830.48,male_female,0.43,"[became, a, famous, scientist, after, the]","[the, content, of, search, engine, index]"
1355,matthewdgonzalez,0.45,3363.65,3363.20,swc,male,1,NaN,0,44100,...,income,377497,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,830.05,830.48,male_male,0.43,"[became, a, famous, scientist, after, the]","[to, catholic, practices]"
1356,popularoutcast,0.13,2160.32,2160.19,swc,female,0,NaN,0,44100,...,deficit,368816,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,236.00,236.37,male_female,0.37,"[predicted, from, historical, price, trends]","[the, argument, here, would, be, a, teleological]"
1357,marcus-bowen,0.28,768.55,768.27,swc,male,1,NaN,0,44100,...,deficit,368816,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,236.00,236.37,male_male,0.37,"[predicted, from, historical, price, trends]","[sixty, eight, year, league, history]"
1358,popularoutcast,0.56,1871.68,1871.12,swc,female,0,NaN,0,44100,...,that,377807,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,1122.21,1122.64,male_female,0.43,"[well, be, at, corporate, sas, as, you, mentio...","[two, words, are, sometimes, hyphenated]"
1359,mnntoino,0.60,3688.52,3687.92,swc,male,1,NaN,0,44100,...,that,377807,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,1122.21,1122.64,male_male,0.43,"[well, be, at, corporate, sas, as, you, mentio...","[around, in]"
1360,popularoutcast,0.25,1417.19,1416.94,swc,female,0,NaN,0,44100,...,trudeau,372436,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,1372.30,1372.77,male_female,0.47,"[its, in, the, medical, doctor, and, doctor]","[italy, and, bring, them, to, the, us]"
1361,mrdallaway,0.32,957.24,956.92,swc,male,1,NaN,0,44100,...,trudeau,372436,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,1372.30,1372.77,male_male,0.47,"[its, in, the, medical, doctor, and, doctor]","[to, architect, thomas, jefferson]"
1362,laura-domineau,0.56,810.00,809.44,swc,female,0,NaN,0,44100,...,prize,367031,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,555.43,555.86,male_female,0.43,"[organizing, science, with]","[polipods, created, by, hasbro]"
1363,mangst,0.59,1109.58,1108.99,swc,male,1,NaN,0,44100,...,prize,367031,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,555.43,555.86,male_male,0.43,"[organizing, science, with]","[page, on, the, website]"
1364,flyingtoaster,0.55,2234.25,2233.70,swc,female,0,NaN,0,44100,...,physics,373732,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,516.80,517.31,male_female,0.51,"[and, published, in, one thousand, nine hundre...","[extensively, by, television, and, newspapers]"
1365,the-epopt,0.43,531.42,530.99,swc,male,1,NaN,0,44100,...,physics,373732,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,516.80,517.31,male_male,0.51,"[and, published, in, one thousand, nine hundre...","[watson, daughter, of, a, prominent]"
1366,thatgirltayler,0.49,214.40,213.91,swc,female,0,NaN,0,44100,...,investigations,370539,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,287.14,288.18,male_female,1.04,"[annual, prize, award, ceremony, on]","[person, running, a, business, without, license]"
1367,99of9-toby-hudson,0.37,3664.88,3664.51,swc,male,1,NaN,0,44100,...,investigations,370539,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,287.14,288.18,male_male,1.04,"[annual, prize, award, ceremony, on]","[the, paired, smell, cannot, detect, leaking]"
1368,sedola,0.32,123.66,123.34,swc,female,0,NaN,0,44100,...,mounted,376286,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,284.17,284.65,male_female,0.48,"[marcus, a, review, of, theory, and, a]","[is, named, after, peter, stuyvesant]"
1369,random2502,0.16,674.54,674.38,swc,male,1,NaN,0,44100,...,mounted,376286,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,284.17,284.65,male_male,0.48,"[marcus, a, review, of, theory, and, a]","[despite, his, having, worked, there, for, ten..."
1370,popularoutcast,0.74,3231.91,3231.17,swc,female,0,NaN,0,44100,...,nine,376624,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,210.25,210.58,male_female,0.33,"[in, reshaping, the, world, consequences, for]","[ethical, political, or, technological]"
1371,readington,0.25,1095.44,1095.19,swc,male,1,NaN,0,44100,...,nine,376624,viktor-o-ledenyov,/om/user/imgriff/datasets/spatial_audio_pipeli...,210.25,210.58,male_male,0.33,"[in, reshaping, the, world, consequences, for]","[such, objects, could, therefore, help]"
1412,popularoutcast,0.14,445.06,444.92,swc,female,0,NaN,0,44100,...,harris,363612,wikipedia,/om/user/imgriff/datasets/spatial_audio_pipeli...,41.34,41.54,female_female,0.20,"[and, attended, western, heights, college]","[sympathizers, were, dealt, a, further, blow]"
1413,the-voice-of-hassocks,0.55,1733.97,1733.42,swc,male,1,NaN,0,44100,...,harris,363612,wikipedia,/om/user/imgriff/datasets/spatial_audio_pipeli...,41.34,41.54,female_male,0.20,"[and, attended, western, heights, college]","[discretion, sometimes, serves, as, well]"
1414,flyingtoaster,0.47,1562.08,1561.61,swc,female,0,NaN,0,44100,...,gold,364074,wikipedia,/om/user/imgriff/datasets/spatial_audio_pipeli...,90.21,90.55,female_female,0.34,"[and, several, friends, were, traveling]","[publishers, they, had, earlier, officially, l..."
1415,shayday,0.33,965.78,965.45,swc,male,1,NaN,0,44100,...,gold,364074,wikipedia,/om/user/imgriff/datasets/spatial_audio_pipeli...,90.21,90.55,female_male,0.34,"[and, several, friends, were, traveling]","[the, degree, to, which, tennyson]"
1416,laurenpt015,0.44,837.87,837.43,swc,female,0,NaN,0,44100,...,throw,364068,wikipedia,/om/user/imgriff/datasets/spatial_audio_pipeli...,85.42,85.91,female_female,0.49,"[and, world, record, holder]","[a, point, frequently, overlooked, in, class]"
1417,borisblue,0.54,628.01,627.47,swc,male,1,NaN,0,44100,...,throw,364068,wikipedia,/om/user/imgriff/datasets/spatial_audio_pipeli...,85.42,85.91,female_male,0.49,"[and, world, record, holder]","[firms, were, divided, into, three, categories]"

In [26]:
import IPython.display as ipd

In [27]:
# b

## Bad examples from manual inspection 
bowie media ex: 8, 9 
wikipedia ex: 36-39

In [28]:
bad_talker_df.iloc[ix].name

1

In [29]:
ix = 19
print(bad_talker_df.iloc[ix])
print(bad_talker_df.iloc[ix]['word'])
ipd.display(ipd.Audio(bad_talker_df.iloc[ix]['cue_src_fn']))
ipd.display(ipd.Audio(bad_talker_df.iloc[ix]['src_fn']))

distractor_client_id                                                    matthewdgonzalez
distractor_clip_dur_in_s                                                            0.45
distractor_clip_end_in_s                                                         3363.65
distractor_clip_start_in_s                                                        3363.2
distractor_corpus                                                                    swc
distractor_gender                                                                   male
distractor_gender_int                                                                  1
distractor_split                                                                     NaN
distractor_split_int                                                                   0
distractor_sr                                                                      44100
distractor_src_fn                      /om/user/imgriff/datasets/spatial_audio_pipeli...
distractor_total_file_duration_in_s                                          4058.820499
distractor_word                                                                 catholic
src_ix                                                                            378270
client_id                                                              viktor-o-ledenyov
clip_dur_in_s                                                                       0.35
clip_end_in_s                                                                     542.48
clip_start_in_s                                                                   542.13
corpus                                                                               swc
gender                                                                              male
gender_int                                                                             1
split                                                                                NaN
split_int                                                                              0
sr                                                                                 44100
src_fn                                 /om/user/imgriff/datasets/spatial_audio_pipeli...
total_file_duration_in_s                                                     3641.003537
word                                                                              famous
cue_word                                                                          income
cue_src_ix                                                                        377497
cue_client_id                                                          viktor-o-ledenyov
cue_src_fn                             /om/user/imgriff/datasets/spatial_audio_pipeli...
cue_clip_start_in_s                                                               830.05
cue_clip_end_in_s                                                                 830.48
gender_cond_td                                                                 male_male
cue_clip_dur_in_s                                                                   0.43
target_transcripts                            [became, a, famous, scientist, after, the]
distractor_transcripts                                         [to, catholic, practices]
Name: 1355, dtype: object
famous

In [30]:
bad_full_df_ixs = [bad_talker_df.iloc[ix].name for ix in [8, 9, 36,37,38,39]]

In [31]:
bad_full_df_ixs

[118, 119, 1412, 1413, 1414, 1415]

In [32]:
final_names_to_exclude = ['viktor-o-ledenyov',  'acerperi']
ok_df = full_swc_manifest[(~full_swc_manifest['client_id'].isin(final_names_to_exclude) ) & (~full_swc_manifest.index.isin(bad_full_df_ixs)) ].reset_index()
ok_df.rename(columns={'index': 'orig_full_index'}, inplace=True)

In [33]:
ok_words, all_words = set(ok_df.word.unique()), set(full_swc_manifest.word.unique())

In [34]:
all_words - ok_words, len(ok_words), len(all_words), len(ok_df)

(set(), 360, 360, 1414)

### Save screened df

In [35]:
out_name = "/om2/user/imgriff/datasets/spatial_audio_pipeline/assets/human_attn_experiment_v00/screened_eval_trial_manifest_new_fnames_w_transcripts.pdpkl"
ok_df.to_pickle(out_name)

In [36]:
ok_df

,orig_full_index,distractor_client_id,distractor_clip_dur_in_s,distractor_clip_end_in_s,distractor_clip_start_in_s,distractor_corpus,distractor_gender,distractor_gender_int,distractor_split,distractor_split_int,...,cue_word,cue_src_ix,cue_client_id,cue_src_fn,cue_clip_start_in_s,cue_clip_end_in_s,gender_cond_td,cue_clip_dur_in_s,target_transcripts,distractor_transcripts
0,0,popularoutcast,0.44,359.92,359.48,swc,female,0,NaN,0,...,dramatic,992746,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1147.51,1147.96,female_female,0.45,"[however, the, cost, for, these, new, types, o...","[made, from, either, dna, or]"
1,1,matthewdgonzalez,0.49,584.65,584.16,swc,male,1,NaN,0,...,dramatic,992746,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1147.51,1147.96,female_male,0.45,"[however, the, cost, for, these, new, types, o...","[in, one thousand, nine hundred and forty, sev..."
2,2,flyingtoaster,0.17,1711.42,1711.25,swc,female,0,NaN,0,...,allows,992957,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1905.81,1906.30,female_female,0.49,"[so, that, they, can, simply, load, in, the, c...","[of, the, core, rule, books, were, slightly, r..."
3,3,warmvoiceover,0.76,487.07,486.31,swc,male,1,NaN,0,...,allows,992957,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1905.81,1906.30,female_male,0.49,"[so, that, they, can, simply, load, in, the, c...","[philadelphia, created, in, seventeen]"
4,4,popularoutcast,0.56,432.21,431.65,swc,female,0,NaN,0,...,with,999423,99of9-toby-hudson,/om/user/imgriff/datasets/spatial_audio_pipeli...,642.92,643.09,male_female,0.17,"[resulted, in, the, death, due, to, a, gas, leak]","[this, was, a, then, unknown, fault]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1409,1435,matthewdgonzalez,0.64,1951.59,1950.95,swc,male,1,NaN,0,...,what,98511,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,220.31,220.61,male_male,0.30,"[and, hurricane, force, wins]","[and, frequently, analyzed]"
1410,1436,popularoutcast,0.62,552.97,552.35,swc,female,0,NaN,0,...,actor,99323,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,6.37,6.68,male_female,0.31,"[bed, chief, wiggum, charging]","[much, earlier]"
1411,1437,incledon,0.49,494.41,493.92,swc,male,1,NaN,0,...,actor,99323,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,6.37,6.68,male_male,0.31,"[bed, chief, wiggum, charging]","[and, south, africa]"
1412,1438,popularoutcast,0.62,956.40,955.78,swc,female,0,NaN,0,...,into,563727,zegoma-beach,/om/user/imgriff/datasets/spatial_audio_pipeli...,213.10,213.29,male_female,0.19,"[is, played, in, the, attack]","[browser, for, windows, mac]"
1413,1439,jdhowens90,0.58,1929.91,1929.33,swc,male,1,NaN,0,...,into,563727,zegoma-beach,/om/user/imgriff/datasets/spatial_audio_pipeli...,213.10,213.29,male_male,0.19,"[is, played, in, the, attack]","[of, the, nazi, germany, which, was, a]"

# Check against other test dfs

In [155]:
swc_mono_manifest = pd.read_pickle(swc_human_stim_path / "cue_and_target_manifest.pdpkl")
swc_mono_manifest

,src_ix,client_id,clip_dur_in_s,clip_end_in_s,clip_start_in_s,corpus,gender,gender_int,split,split_int,...,src_fn,total_file_duration_in_s,word,cue_word,cue_src_ix,cue_client_id,cue_src_fn,cue_clip_start_in_s,cue_clip_end_in_s,cue_clip_dur_in_s
0,992601,1904-cc,0.22,969.29,969.07,swc,female,0,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,2207.180045,these,dramatic,992746,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1147.51,1147.96,0.45
1,993029,1904-cc,0.30,1989.34,1989.04,swc,female,0,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,2207.180045,simply,allows,992957,1904-cc,/om/user/imgriff/datasets/spatial_audio_pipeli...,1905.81,1906.30,0.49
2,1003750,99of9-toby-hudson,0.35,3718.62,3718.27,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,3793.117460,death,with,999423,99of9-toby-hudson,/om/user/imgriff/datasets/spatial_audio_pipeli...,642.92,643.09,0.17
3,845840,a-c-norman,0.39,22.72,22.33,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,2175.444172,english,purchased,847874,a-c-norman,/om/user/imgriff/datasets/spatial_audio_pipeli...,1953.25,1953.69,0.44
4,226810,a-parrot,0.51,1542.51,1542.00,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,3338.366259,system,twelve,226218,a-parrot,/om/user/imgriff/datasets/spatial_audio_pipeli...,905.52,906.05,0.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,105077,zanimum,0.55,262.95,262.40,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,617.248798,forces,generated,96674,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,501.23,501.84,0.61
716,101856,zanimum,0.40,480.30,479.90,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,3221.953016,times,reference,105698,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,607.63,608.22,0.59
717,97804,zanimum,0.44,622.74,622.30,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,1220.892154,force,what,98511,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,220.31,220.61,0.30
718,105477,zanimum,0.32,300.58,300.26,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,988.727438,chief,actor,99323,zanimum,/om/user/imgriff/datasets/spatial_audio_pipeli...,6.37,6.68,0.31
719,563479,zegoma-beach,0.38,23.16,22.78,swc,male,1,NaN,0,...,/om/user/imgriff/datasets/spatial_audio_pipeli...,479.647347,attack,into,563727,zegoma-beach,/om/user/imgriff/datasets/spatial_audio_pipeli...,213.10,213.29,0.19